import {useEffect,useRef,useState} from 'react';
import {Button} from '@/ui/Button';
export function BankCamera({onCapture,onClose}:{onCapture:(file:File)=>void;onClose:()=>void}){
 const video=useRef<HTMLVideoElement>(null),stream=useRef<MediaStream|null>(null),generation=useRef(0);const [devices,setDevices]=useState<MediaDeviceInfo[]>([]),[selected,setSelected]=useState(''),[pending,setPending]=useState(false),[ready,setReady]=useState(false),[error,setError]=useState('');
 function stop(){generation.current++;stream.current?.getTracks().forEach(track=>track.stop());stream.current=null;}
 async function start(deviceId=''){
  stop();const attempt=generation.current;setPending(true);setReady(false);setError('');
  if(!navigator.mediaDevices?.getUserMedia){setError('La caméra nécessite HTTPS et un navigateur compatible. Importez un fichier à la place.');setPending(false);return;}
  const timeout=window.setTimeout(()=>{if(attempt===generation.current){stop();setPending(false);setError('L’accès à la caméra n’a pas été confirmé. Fermez puis réessayez, ou importez un fichier.');}},20000);
  try{const value=await navigator.mediaDevices.getUserMedia({audio:false,video:deviceId?{deviceId:{exact:deviceId}}:{facingMode:{ideal:'environment'},width:{ideal:1920},height:{ideal:1080}}});if(attempt!==generation.current){value.getTracks().forEach(track=>track.stop());return;}stream.current=value;if(video.current){video.current.srcObject=value;await video.current.play();}const available=await navigator.mediaDevices.enumerateDevices();if(attempt===generation.current){setDevices(available.filter(d=>d.kind==='videoinput'));setSelected(value.getVideoTracks()[0]?.getSettings().deviceId||deviceId);setReady(true);}}
  catch(cause){if(attempt!==generation.current)return;setPending(false);stop();const name=cause instanceof DOMException?cause.name:'';setError(name==='NotAllowedError'?'Accès à la caméra refusé. Autorisez-la dans les réglages du navigateur ou importez un fichier.':name==='NotFoundError'?'Aucune caméra reconnue. Branchez une webcam ou importez un fichier.':name==='NotReadableError'?'La caméra est utilisée par une autre application ou indisponible. Fermez cette application puis réessayez.':'La caméra n’a pas pu démarrer. Importez un fichier ou réessayez.');}
  finally{clearTimeout(timeout);if(attempt===generation.current)setPending(false);}
 }
 useEffect(()=>{void start();return()=>stop();},[]);
 async function capture(){const source=video.current;if(!source?.videoWidth||!ready)return;const attempt=generation.current;setPending(true);const factor=Math.min(1,2000/Math.max(source.videoWidth,source.videoHeight)),canvas=document.createElement('canvas');canvas.width=Math.round(source.videoWidth*factor);canvas.height=Math.round(source.videoHeight*factor);canvas.getContext('2d')!.drawImage(source,0,0,canvas.width,canvas.height);const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,'image/jpeg',.9));if(attempt!==generation.current)return;if(!blob){setError('La photo n’a pas pu être capturée. Réessayez.');setPending(false);return;}stop();onCapture(new File([blob],'rib-photo.jpg',{type:'image/jpeg'}));onClose();}
 return <section aria-label="Appareil photo du RIB" style={{display:'grid',gap:12,border:'1px solid var(--line)',padding:16}}><h3>Photographier votre RIB</h3><p>Cadrez le document à plat, net et sans reflet. Un téléphone apparaît ici uniquement si votre ordinateur le reconnaît comme webcam.</p>{error&&<p role="alert">{error}</p>}<video ref={video} autoPlay muted playsInline aria-label="Aperçu de la caméra" style={{width:'100%',maxHeight:360,background:'#102030'}}/>{devices.length>1&&<label>Caméra<select value={selected} disabled={pending} onChange={e=>void start(e.target.value)}>{devices.map((device,index)=><option key={device.deviceId} value={device.deviceId}>{device.label||`Caméra ${index+1}`}</option>)}</select></label>}{pending&&<p role="status">Ouverture de la caméra…</p>}<div style={{display:'flex',gap:12,flexWrap:'wrap'}}><Button type="button" onClick={()=>void capture()} disabled={!ready||pending}>Prendre la photo</Button>{error&&<Button type="button" variant="outline" onClick={()=>void start()} disabled={pending}>Réessayer la caméra</Button>}<Button type="button" variant="outline" onClick={()=>{stop();onClose();}}>Fermer la caméra</Button></div></section>;
}
