import { useRef, useState, type FormEvent } from 'react';
import { api } from '@/services/api';
import { Button } from '@/ui/Button';
import { Checkbox } from '@/ui/Choice';
import u from './NurseUI.module.css';
type BankFile={id:string;mime:string;size_bytes:number;created_at:string};
export function BankDocument({document,onSaved}:{document:BankFile|null;onSaved:()=>void}) {
  const [file,setFile]=useState<File|null>(null),[fictional,setFictional]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
  const pending=useRef(false),key=useRef('');
  function choose(value:File|null){setError('');setMessage('');setFictional(false);key.current=crypto.randomUUID();if(value&&(value.size>3*1024*1024||!['application/pdf','image/jpeg','image/png'].includes(value.type))){setFile(null);setError('Choisissez un PDF, JPEG ou PNG de 3 Mo maximum.');return;}setFile(value);}
  async function upload(event:FormEvent){event.preventDefault();if(pending.current||!file||!fictional)return;pending.current=true;setBusy(true);setError('');setMessage('');try{const contentBase64=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(new Error('Lecture du fichier impossible.'));reader.readAsDataURL(file);});await api('/me/bank-document',{method:'PUT',key:key.current,body:{mime:file.type,contentBase64,fictional:true}});setFile(null);setFictional(false);setMessage('RIB de démonstration enregistré.');onSaved();}catch(cause){setError(cause instanceof Error?cause.message:'Le dépôt n’a pas été confirmé.');}finally{pending.current=false;setBusy(false);}}
  async function download(){if(pending.current)return;pending.current=true;setBusy(true);setError('');try{const base=(import.meta.env.VITE_API_URL||'/api/v1').replace(/\/$/,'');const response=await fetch(base+'/me/bank-document',{credentials:'include',cache:'no-store'});if(!response.ok)throw new Error('Ce RIB est indisponible ou inaccessible. Réessayez.');const blob=await response.blob(),url=URL.createObjectURL(blob),link=window.document.createElement('a');link.href=url;link.download='rib-fictif.'+(blob.type.includes('pdf')?'pdf':blob.type.includes('png')?'png':'jpg');window.document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}catch(cause){setError(cause instanceof Error?cause.message:'Téléchargement indisponible.');}finally{pending.current=false;setBusy(false);}}
  return <section className={u.card} id="rib" tabIndex={-1}><h2>Mon RIB de démonstration</h2><p>Importez un fichier ou prenez une photo avec votre appareil. Il n’y a pas de lecture automatique de l’IBAN. Le nouveau fichier remplace le RIB précédent ou les coordonnées structurées.</p>{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}{document&&<p>Fichier enregistré le {new Date(document.created_at).toLocaleDateString('fr-FR')} · {Math.ceil(document.size_bytes/1024)} Ko <Button variant="outline" disabled={busy} onClick={download}>Télécharger mon RIB</Button></p>}
    <form onSubmit={upload} style={{display:'grid',gridTemplateColumns:'minmax(0,1fr)',gap:16,marginTop:16,minWidth:0}}><fieldset disabled={busy} style={{display:'grid',gridTemplateColumns:'minmax(0,1fr)',gap:16,border:0,padding:0,minWidth:0}}><legend>Ajouter un fichier RIB fictif</legend><label>Importer un RIB (PDF, JPEG ou PNG)<input style={{width:"100%",minWidth:0}} type="file" accept="application/pdf,image/jpeg,image/png" onChange={e=>choose(e.target.files?.[0]||null)}/></label><label>Prendre une photo du RIB<input style={{width:"100%",minWidth:0}} type="file" accept="image/jpeg,image/png" capture="environment" onChange={e=>choose(e.target.files?.[0]||null)}/></label><p>3 Mo maximum. L’appareil photo est proposé selon votre navigateur ; vous pouvez toujours importer un fichier. {file&&`Sélection : ${file.name}`}</p><Checkbox checked={fictional} onChange={e=>setFictional(e.target.checked)} required>Ce RIB contient uniquement des données fictives.</Checkbox><Button style={{whiteSpace:"normal",height:"auto",minHeight:44}} type="submit" disabled={!file||!fictional} loading={busy}>Enregistrer mon fichier RIB</Button></fieldset></form>
  </section>;
}
