import {useEffect,useRef,useState,type FormEvent} from 'react';
import {api} from '@/services/api';
import {Button} from '@/ui/Button';
import {TextField} from '@/ui/Field';
import {Checkbox} from '@/ui/Choice';
import {BankCamera} from './BankCamera';
import {completeBankText,emptyBankFields,frenchBankParts,normalizeIban,parseBankText,validBic,validIban,type BankFields} from '@/lib/bankFields';
import u from './NurseUI.module.css';
type BankFile={id:string;mime:string;size_bytes:number;created_at:string};
export function BankDocument({document:attachment,details,onSaved}:{document:BankFile|null;details:BankFields|null;onSaved:()=>void}){
 const [fields,setFields]=useState<BankFields>(details||emptyBankFields),[file,setFile]=useState<File|null>(null),[stage,setStage]=useState<'capture'|'review'|'saved'>(details?'saved':'capture'),[reviewed,setReviewed]=useState(false),[camera,setCamera]=useState(false),[busy,setBusy]=useState(false),[analyzing,setAnalyzing]=useState(false),[progress,setProgress]=useState(''),[failures,setFailures]=useState(0),[error,setError]=useState(''),[message,setMessage]=useState('');
 const abort=useRef<AbortController|null>(null),mounted=useRef(true),pending=useRef(false),key=useRef(crypto.randomUUID()),fileInput=useRef<HTMLInputElement>(null);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;abort.current?.abort();};},[]);
 function choose(value:File|null,recognizedText?:string){if(!value)return;setError('');setMessage('');if(value.size>3*1024*1024||!['application/pdf','image/jpeg','image/png'].includes(value.type)){setError('Choisissez un PDF, JPEG ou PNG de 3 Mo maximum.');return;}abort.current?.abort('replaced');setReviewed(false);key.current=crypto.randomUUID();setFailures(0);setFields(emptyBankFields());setFile(value);setStage('capture');setCamera(false);void analyze(value,recognizedText);}

 const parts=frenchBankParts(fields.iban);
 function change(name:keyof BankFields,value:string){setFields(old=>({...old,[name]:name==='iban'?normalizeIban(value):name==='bic'?value.replace(/\s/g,'').toUpperCase():value}));setReviewed(false);key.current=crypto.randomUUID();}
 function manual(){abort.current?.abort('manual');setAnalyzing(false);setCamera(false);setStage('review');setReviewed(false);}
 async function analyze(source:File|null=file,recognizedText?:string){if(!source)return;abort.current?.abort();const controller=new AbortController();abort.current=controller;setAnalyzing(true);setProgress('Lecture automatique du document…');setError('');setMessage('');setReviewed(false);let timeout:number|undefined;
  try{const {analyzeBankFile}=await import('@/lib/bankOcr');const readAutomatically=async()=>{
   if(recognizedText!==undefined){
    const detected=parseBankText(recognizedText);
    if(!controller.signal.aborted&&mounted.current&&abort.current===controller){setFields(detected);if(Object.values(detected).some(Boolean))setStage('review');}
    if(completeBankText(recognizedText))return recognizedText;
    setProgress('Photo prise. Analyse automatique des champs restants…');
   }
   const fullText=await analyzeBankFile(source,controller.signal,value=>{if(!controller.signal.aborted&&mounted.current&&abort.current===controller)setProgress(value);});
   return recognizedText===undefined?fullText:recognizedText+'\n'+fullText;
  };const text=await Promise.race([readAutomatically(),new Promise<never>((_,reject)=>{timeout=window.setTimeout(()=>{controller.abort('timeout');reject(new Error('L’analyse a dépassé 45 secondes. Vous pouvez compléter les champs manuellement.'));},45000);}),new Promise<never>((_,reject)=>controller.signal.addEventListener('abort',()=>reject(new Error('Analyse interrompue.')),{once:true}))]);if(!mounted.current||controller.signal.aborted||abort.current!==controller)return;const parsed=parseBankText(text);setFields(old=>Object.fromEntries(Object.entries(old).map(([name,value])=>[name,parsed[name as keyof BankFields]||value])) as BankFields);if(!parsed.iban||!parsed.holder){setFailures(n=>n+1);setMessage('Lecture partielle : vérifiez et complétez les champs manquants. Aucune donnée manquante n’a été inventée.');}else setMessage('Lecture terminée sur cet appareil. Vérifiez chaque champ avec votre RIB avant d’enregistrer.');setStage('review');}
  catch(cause){if(!mounted.current||abort.current!==controller||controller.signal.reason==='manual')return;setFailures(n=>n+1);setError(cause instanceof Error&&!controller.signal.aborted?cause.message:'L’analyse n’a pas abouti. Complétez les champs manuellement ou essayez un document plus lisible.');setStage('review');}
  finally{clearTimeout(timeout);if(mounted.current&&abort.current===controller)setAnalyzing(false);}
 }
 async function save(event:FormEvent){event.preventDefault();if(pending.current)return;setError('');const clean={iban:normalizeIban(fields.iban),bic:fields.bic.trim().toUpperCase(),holder:fields.holder.trim(),bankName:fields.bankName.trim()};if(!validIban(clean.iban)){setError('L’IBAN est incomplet ou sa clé de contrôle est invalide. Vérifiez-le sur votre RIB.');return;}if(clean.bic&&!validBic(clean.bic)){setError('Le BIC doit contenir 8 ou 11 caractères valides.');return;}if(clean.holder.length<2||clean.holder.length>150||clean.bankName.length>150){setError('Renseignez le titulaire (2 à 150 caractères) ; le nom de banque est limité à 150 caractères.');return;}if(!reviewed){setError('Confirmez avoir vérifié les coordonnées avant de les enregistrer.');return;}pending.current=true;setBusy(true);try{const body={...clean,reviewed:true};if(file){const contentBase64=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(new Error('Lecture du fichier impossible.'));reader.readAsDataURL(file);});await api('/me/bank-document',{method:'PUT',key:key.current,body:{...body,mime:file.type,contentBase64}});}else await api('/me/bank-details',{method:'PUT',key:key.current,body});setFields(clean);setFailures(0);setStage('saved');setMessage('Vos coordonnées bancaires ont été enregistrées.');setFile(null);onSaved();}catch(cause){setError(cause instanceof Error?cause.message:'L’enregistrement n’a pas été confirmé.');}finally{pending.current=false;setBusy(false);}}
 async function download(){setError('');try{const base=(import.meta.env.VITE_API_URL||'/api/v1').replace(/\/$/,'');const response=await fetch(base+'/me/bank-document',{credentials:'include',cache:'no-store'});if(!response.ok)throw new Error('Ce RIB est indisponible ou inaccessible. Réessayez.');const blob=await response.blob(),url=URL.createObjectURL(blob),link=window.document.createElement('a');link.href=url;link.download='rib.'+(blob.type.includes('pdf')?'pdf':blob.type.includes('png')?'png':'jpg');window.document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}catch(cause){setError(cause instanceof Error?cause.message:'Téléchargement indisponible.');}}
 return <section className={u.card} id="rib" tabIndex={-1}><h2>Mon RIB</h2><p>1. Photo et analyse automatiques · 2. Vérifier les coordonnées · 3. Enregistrer</p><p>La lecture automatique reste sur votre appareil. Le fichier et les champs vérifiés sont envoyés à votre espace InfiMatch uniquement lorsque vous confirmez l’enregistrement.</p>{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}
  {stage==='saved'?<><h3>Coordonnées enregistrées</h3><dl><dt>Titulaire</dt><dd>{fields.holder}</dd><dt>IBAN</dt><dd style={{overflowWrap:'anywhere'}}>{fields.iban}</dd><dt>BIC</dt><dd>{fields.bic||'Non renseigné'}</dd><dt>Banque</dt><dd>{fields.bankName||'Non renseignée'}</dd></dl><Button variant="outline" onClick={()=>{setStage('capture');setReviewed(false);}}>Modifier mon RIB</Button></>:<>
   <div style={{display:'flex',flexWrap:'wrap',gap:12,marginBlock:16}}><Button type="button" disabled={busy||analyzing||camera} onClick={()=>setCamera(true)}>Ouvrir la caméra</Button><Button type="button" variant="outline" disabled={busy||analyzing} onClick={()=>fileInput.current?.click()}>Importer PDF ou photo</Button><Button type="button" variant="ghost" disabled={busy} onClick={manual}>Saisir ou corriger manuellement</Button></div>
   <input ref={fileInput} type="file" accept="application/pdf,image/jpeg,image/png" aria-label="Importer un RIB (PDF, JPEG ou PNG)" onChange={event=>{choose(event.target.files?.[0]||null);event.target.value='';}} disabled={busy||analyzing} style={{display:'none'}}/><p>PDF, JPEG ou PNG : 3 Mo maximum. Analyse limitée à 3 pages PDF et 45 secondes ; seules les deux premières pages scannées sont reconnues.</p>
   {camera&&<BankCamera onCapture={choose} onClose={()=>setCamera(false)}/>}
   {file&&<p>Document sélectionné : {file.name} <Button type="button" variant="ghost" disabled={busy||analyzing} onClick={()=>{setFile(null);setReviewed(false);key.current=crypto.randomUUID();}}>Retirer le fichier</Button></p>}
   {file&&!analyzing&&failures>0&&<Button type="button" disabled={analyzing||busy||camera} onClick={()=>void analyze(file)}>{analyzing?'Analyse locale en cours…':'Relancer l’analyse du document'}</Button>}
   {analyzing&&<><p role="status">{progress}</p><Button type="button" variant="outline" onClick={manual}>Arrêter l’analyse et saisir manuellement</Button></>}
   {failures>=2&&<p role="status">Deux analyses n’ont pas fourni tous les champs. Continuez manuellement : les informations déjà reconnues sont conservées.</p>}
   {stage==='review'&&<form onSubmit={save} noValidate style={{display:'grid',gap:16,marginTop:20,minWidth:0}}><h3>Vérifier les coordonnées</h3><TextField label="Titulaire du compte" value={fields.holder} onChange={e=>change('holder',e.target.value)} maxLength={150} required disabled={busy||analyzing}/><TextField label="IBAN" value={fields.iban} onChange={e=>change('iban',e.target.value)} autoComplete="off" maxLength={42} required disabled={busy||analyzing}/><TextField label="BIC" value={fields.bic} onChange={e=>change('bic',e.target.value)} autoComplete="off" maxLength={11} optional hint="Vous pouvez laisser ce champ vide si le BIC ne figure pas sur votre RIB." disabled={busy||analyzing}/><TextField label="Nom de la banque" value={fields.bankName} onChange={e=>change('bankName',e.target.value)} maxLength={150} optional disabled={busy||analyzing}/><p>{file?'Le fichier sélectionné et ces champs seront enregistrés ensemble.':'La saisie sans fichier remplace le RIB précédent et retire sa pièce jointe éventuelle.'}</p><Checkbox checked={reviewed} onChange={e=>setReviewed(e.target.checked)} disabled={busy||analyzing}>J’ai vérifié ces coordonnées sur mon RIB et je confirme leur exactitude.</Checkbox><Button type="submit" loading={busy} disabled={analyzing||!reviewed}>Enregistrer mon RIB vérifié</Button></form>}
  </>}
  {parts&&<dl aria-label="Références bancaires françaises"><dt>Code banque</dt><dd>{parts.bank}</dd><dt>Code guichet</dt><dd>{parts.branch}</dd><dt>Numéro de compte</dt><dd>{parts.account}</dd><dt>Clé RIB</dt><dd>{parts.key}</dd></dl>}
  {attachment&&<p>Pièce jointe enregistrée le {new Date(attachment.created_at).toLocaleDateString('fr-FR')} · {Math.ceil(attachment.size_bytes/1024)} Ko <Button variant="outline" onClick={()=>void download()} disabled={busy||analyzing}>Télécharger mon RIB</Button></p>}
 </section>;
}
