import {useEffect,useRef,useState} from 'react';
import {Button} from '@/ui/Button';
import {parseBankText} from '@/lib/bankFields';
export function BankCamera({onCapture,onClose}:{onCapture:(file:File,text?:string)=>void;onClose:()=>void}){
 const video=useRef<HTMLVideoElement>(null),stream=useRef<MediaStream|null>(null),generation=useRef(0),scanner=useRef<AbortController|null>(null),capturing=useRef(false);
 const callbacks=useRef({onCapture,onClose});callbacks.current={onCapture,onClose};
 const [devices,setDevices]=useState<MediaDeviceInfo[]>([]),[selected,setSelected]=useState(''),[pending,setPending]=useState(false),[ready,setReady]=useState(false),[error,setError]=useState(''),[status,setStatus]=useState('');
 function stop(){generation.current++;scanner.current?.abort();stream.current?.getTracks().forEach(track=>track.stop());stream.current=null;}
 async function start(deviceId=''){
  stop();capturing.current=false;const attempt=generation.current;setPending(true);setReady(false);setError('');setStatus('');
  if(!navigator.mediaDevices?.getUserMedia){setError('La caméra nécessite HTTPS et un navigateur compatible. Importez un fichier à la place.');setPending(false);return;}
  const timeout=window.setTimeout(()=>{if(attempt===generation.current){stop();setPending(false);setError('L’accès à la caméra n’a pas été confirmé. Fermez puis réessayez, ou importez un fichier.');}},20000);
  try{const value=await navigator.mediaDevices.getUserMedia({audio:false,video:deviceId?{deviceId:{exact:deviceId}}:{facingMode:{ideal:'environment'},width:{ideal:1920},height:{ideal:1080}}});if(attempt!==generation.current){value.getTracks().forEach(track=>track.stop());return;}stream.current=value;if(video.current){video.current.srcObject=value;await video.current.play();}const available=await navigator.mediaDevices.enumerateDevices();if(attempt===generation.current){setDevices(available.filter(d=>d.kind==='videoinput'));setSelected(value.getVideoTracks()[0]?.getSettings().deviceId||deviceId);setReady(true);}}
  catch(cause){if(attempt!==generation.current)return;setPending(false);stop();const name=cause instanceof DOMException?cause.name:'';setError(name==='NotAllowedError'?'Accès à la caméra refusé. Autorisez-la dans les réglages du navigateur ou importez un fichier.':name==='NotFoundError'?'Aucune caméra reconnue. Branchez une webcam ou importez un fichier.':name==='NotReadableError'?'La caméra est utilisée par une autre application ou indisponible. Fermez cette application puis réessayez.':'La caméra n’a pas pu démarrer. Importez un fichier ou réessayez.');}
  finally{clearTimeout(timeout);if(attempt===generation.current)setPending(false);}
 }
 function frame(){const source=video.current;if(!source?.videoWidth||source.readyState<2)return null;const factor=Math.min(1,2000/Math.max(source.videoWidth,source.videoHeight)),canvas=document.createElement('canvas');canvas.width=Math.round(source.videoWidth*factor);canvas.height=Math.round(source.videoHeight*factor);canvas.getContext('2d')!.drawImage(source,0,0,canvas.width,canvas.height);return canvas;}
 async function capture(canvas=frame(),text?:string){if(!canvas||capturing.current)return;capturing.current=true;const attempt=generation.current;scanner.current?.abort();setPending(true);const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,'image/jpeg',.9));if(attempt!==generation.current)return;if(!blob){capturing.current=false;setError('La photo n’a pas pu être capturée. Réessayez.');setPending(false);return;}stop();callbacks.current.onCapture(new File([blob],'rib-photo.jpg',{type:'image/jpeg'}),text);callbacks.current.onClose();}
 useEffect(()=>{void start();return()=>stop();},[]);
 useEffect(()=>{
  if(!ready)return;
  const controller=new AbortController();scanner.current=controller;let timer:number|undefined,deadline:number|undefined;let previous='';
  deadline=window.setTimeout(()=>{controller.abort();setStatus('La détection prend du temps. Vous pouvez prendre la photo ou importer un document plus net.');},60000);
  void (async()=>{
   try{setStatus('Préparation de la lecture automatique…');const {createBankCameraReader}=await import('@/lib/bankOcr');if(controller.signal.aborted)return;const reader=await createBankCameraReader(controller.signal);
    const scan=async()=>{if(controller.signal.aborted||capturing.current)return;try{const canvas=frame();if(canvas){setStatus('Recherche des coordonnées… Gardez le RIB entier dans le cadre.');const text=await reader.read(canvas);if(controller.signal.aborted)return;const fields=parseBankText(text);if(fields.iban&&fields.iban===previous){clearTimeout(deadline);setStatus('IBAN reconnu. Photo prise automatiquement.');await capture(canvas,text);return;}previous=fields.iban;if(previous)setStatus('Coordonnées détectées. Gardez le document immobile…');}timer=window.setTimeout(()=>void scan(),900);}catch{if(!controller.signal.aborted){controller.abort();clearTimeout(deadline);setStatus('La lecture automatique est indisponible. Vous pouvez prendre la photo.');}}};
    await scan();
   }catch{if(!controller.signal.aborted){controller.abort();clearTimeout(deadline);setStatus('La lecture automatique est indisponible. Vous pouvez prendre la photo.');}}
  })();
  return()=>{clearTimeout(timer);clearTimeout(deadline);controller.abort();};
 },[ready,selected]);
 return <section aria-label="Appareil photo du RIB" style={{display:'grid',gap:12,border:'1px solid var(--line)',padding:16}}><h3>Photographier votre RIB</h3><p>Cadrez le RIB entier, à plat et sans reflet. La photo est prise automatiquement dès que l’IBAN est lisible et stable, puis les coordonnées reconnues remplissent les champs.</p>{error&&<p role="alert">{error}</p>}<video ref={video} autoPlay muted playsInline aria-label="Aperçu de la caméra" style={{width:'100%',maxHeight:360,background:'#102030'}}/>{devices.length>1&&<label>Caméra<select value={selected} disabled={pending} onChange={e=>void start(e.target.value)}>{devices.map((device,index)=><option key={device.deviceId} value={device.deviceId}>{device.label||`Caméra ${index+1}`}</option>)}</select></label>}{pending&&<p role="status">{capturing.current?'Capture de la photo…':'Ouverture de la caméra…'}</p>}{status&&<p role="status">{status}</p>}<div style={{display:'flex',gap:12,flexWrap:'wrap'}}><Button type="button" onClick={()=>void capture()} disabled={!ready||pending}>Prendre la photo</Button>{error&&<Button type="button" variant="outline" onClick={()=>void start()} disabled={pending}>Réessayer la caméra</Button>}<Button type="button" variant="outline" onClick={()=>{stop();onClose();}}>Fermer la caméra</Button></div></section>;
}
