import {useState} from 'react';
import type {ProfessionalProfile} from '@/services/profile';
import {cvDiplomaField,reviewedCvProfile,type CvSuggestions} from '@/lib/cvReview';
import {Button} from '@/ui/Button';
import {TextField} from '@/ui/Field';
const identityLabels={firstName:'Prénom',lastName:'Nom',email:'Email',phone:'Téléphone',city:'Ville',postalCode:'Code postal'};
export function CvProfileReview({suggestions,profile,onApply}:{suggestions:CvSuggestions;profile:ProfessionalProfile;onApply:(value:Partial<ProfessionalProfile>)=>void}) {
 const [diplomas,setDiplomas]=useState(()=>suggestions.diplomas.map(d=>({...d,selected:false})));
 const [skills,setSkills]=useState(()=>suggestions.skills.map(s=>({...s,selected:false})));
 const [reviewed,setReviewed]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 function apply(){setError('');setMessage('');try{onApply(reviewedCvProfile(profile,diplomas.filter(d=>d.selected),skills.filter(s=>s.selected)));setReviewed(false);setDiplomas(rows=>rows.map(r=>({...r,selected:false})));setSkills(rows=>rows.map(r=>({...r,selected:false})));setMessage('Les éléments retenus ont été ajoutés au formulaire. Vérifiez les années de chaque diplôme puis enregistrez votre profil. Une année absente du CV conserve celle déjà renseignée ; sinon elle reste à compléter.');}catch(e){setError(e instanceof Error?e.message:'Vérifiez les propositions.');}}
 return <section aria-label="Autres informations proposées par le CV" style={{display:'grid',gridTemplateColumns:'minmax(0,1fr)',minWidth:0,gap:12,overflowWrap:'anywhere'}}>
 <h4>Informations à vérifier</h4><p>La lecture du CV ne certifie aucun diplôme ni aucune compétence. Aucun élément ci-dessous n’est sélectionné automatiquement.</p>
 {Object.keys(suggestions.identity).length>0&&<><h5>Identité et coordonnées repérées</h5><p>Vos informations personnelles sont protégées. Pour les modifier, utilisez la <a href="#informations-personnelles">demande de correction des informations personnelles</a>.</p><dl>{Object.entries(suggestions.identity).map(([key,item])=>item&&<div key={key}><dt>{identityLabels[key as keyof typeof identityLabels]}</dt><dd>{item.value}<details><summary>Extrait et précautions</summary><p>{item.evidence}</p>{item.warnings.map((w,i)=><p key={i}>{w}</p>)}</details></dd></div>)}</dl></>}
 {diplomas.length>0&&<><h5>Diplômes proposés</h5>{diplomas.map((d,i)=>{const current=profile.details?.[cvDiplomaField[d.qualification]];return <div key={i} style={{border:'1px solid var(--line)',padding:12}}><label><input type="checkbox" checked={d.selected} onChange={e=>{setDiplomas(rows=>rows.map((r,n)=>n===i?{...r,selected:e.target.checked}:r));setReviewed(false);}}/> {current!==undefined?`Remplacer explicitement l’année ${current} du diplôme ${d.qualification}`:`Retenir le diplôme ${d.qualification}`}</label><TextField label={`Année du diplôme ${d.qualification} proposé ${i+1}`} type="number" min={1900} max={new Date().getFullYear()} value={d.year??''} onChange={e=>{setDiplomas(rows=>rows.map((r,n)=>n===i?{...r,year:e.target.value?Number(e.target.value):null}:r));setReviewed(false);}}/><details><summary>Extrait et précautions</summary><p>{d.evidence}</p>{d.warnings.map((w,n)=><p key={n}>{w}</p>)}</details></div>;})}<p>Une année non reconnue ne bloque pas l’application : l’année existante est conservée, sinon vous pourrez la compléter dans le profil. Retenir IADE ou IBODE ajoute aussi IDE ; son année d’obtention reste indépendante et doit être renseignée séparément.</p></>}
 {skills.length>0&&<><h5>Compétences proposées</h5>{skills.map((s,i)=><div key={s.code}><label><input type="checkbox" disabled={profile.skills.includes(s.code)} checked={s.selected} onChange={e=>{setSkills(rows=>rows.map((r,n)=>n===i?{...r,selected:e.target.checked}:r));setReviewed(false);}}/> {s.label}{profile.skills.includes(s.code)?' — déjà dans le profil':''}</label><details><summary>Extrait et précautions</summary><p>{s.evidence}</p>{s.warnings.map((w,n)=><p key={n}>{w}</p>)}</details></div>)}</>}
 {!!suggestions.services?.length&&<p>Services repérés : {suggestions.services.map(s=>s.label).join(', ')}. Vérifiez vos choix d’exercice dans la rubrique <a href="#competences">Compétences</a> ; une mention dans un CV n’indique pas automatiquement votre préférence actuelle.</p>}
 {(diplomas.length>0||skills.length>0)&&<><label><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/> J’ai vérifié les éléments sélectionnés et j’accepte les remplacements d’années explicitement cochés.</label><Button type="button" style={{whiteSpace:'normal',maxWidth:'100%'}} disabled={!reviewed||!([...diplomas,...skills].some(r=>r.selected))} onClick={apply}>Appliquer les informations vérifiées au formulaire</Button></>}
 {error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}
 </section>;
}
