import {useState} from 'react';
import {Link} from 'react-router';
import {filterGuides,type HelpRole} from '@/data/helpGuides';
import {TextField,SelectField} from '@/ui/Field';
export function HelpGuides({initialRole='ALL',admin=false}:{initialRole?:HelpRole;admin?:boolean}) {
 const videoByRole:Partial<Record<HelpRole,string>>={NURSE:'interimaire',ESTABLISHMENT:'etablissement',AGENCY:'agence',ADMIN:'administrateur'};
 const [query,setQuery]=useState(''),[role,setRole]=useState<HelpRole>(initialRole);const guides=filterGuides(query,role),video=videoByRole[role];
 return <section aria-labelledby="help-guides"><h2 id="help-guides">Mode d’emploi et questions fréquentes</h2><p>Guides écrits mis à jour le 19 septembre 2026. Les actions disponibles dépendent de votre rôle et de l’état de la mission.</p><div style={{display:'grid',gap:16}}><TextField label="Rechercher dans l’aide" type="search" value={query} maxLength={150} onChange={e=>setQuery(e.target.value)}/><SelectField label="Votre espace" value={role} onChange={e=>setRole(e.target.value as HelpRole)}><option value="ALL">Tous les espaces</option><option value="NURSE">Intérimaire</option><option value="ESTABLISHMENT">Établissement</option><option value="AGENCY">Agence</option><option value="ADMIN">Administrateur</option></SelectField></div><p role="status">{guides.length} guide(s)</p>{guides.map(g=><details key={g.id} style={{padding:16,border:'1px solid var(--line)',borderRadius:12,marginBlock:12}}><summary>{g.title}</summary><ol>{g.steps.map((step,i)=><li key={i} style={{marginBlock:10}}>{step}</li>)}</ol>{g.href&&!admin&&<Link to={g.href}>{g.label}</Link>}</details>)}{video&&<details style={{marginBlock:20}}><summary>Vidéo : trouver les guides de cet espace</summary><p>Courte démonstration de navigation de l’aide sur une interface locale, sans données personnelles. Elle ne montre pas une affectation ou un envoi réel.</p><video key={video} controls preload="none" poster={'/guides/'+video+'.jpg'} style={{maxWidth:'100%',width:720}} aria-label="Démonstration de navigation de l’aide"><source src={'/guides/'+video+'.webm'} type="video/webm"/><track kind="captions" src={'/guides/'+video+'.vtt'} srcLang="fr" label="Français" default/>Votre navigateur ne peut pas lire cette vidéo.</video><h3>Version écrite de la vidéo</h3><ol><li>Ouvrez Aide et support.</li><li>Sélectionnez votre espace puis recherchez un sujet.</li><li>Ouvrez le guide proposé et lisez les étapes.</li><li>Faites défiler le guide pour retrouver les liens vers les pages utiles. Les actions dépendent de vos droits.</li></ol><a href={'/guides/'+video+'.jpg'}>Voir la capture du guide</a></details>}{!guides.length&&<p>Aucun guide trouvé. Essayez un autre terme ou contactez le support.</p>}</section>;
}
