import {useEffect,useState} from 'react';
import {Link} from 'react-router';
import {filterGuides,type HelpRole} from '@/data/helpGuides';
import {helpTutorials} from '@/data/helpTutorials';
import {TextField,SelectField} from '@/ui/Field';
import s from './HelpGuides.module.css';
export function HelpGuides({initialRole='ALL',admin=false}:{initialRole?:HelpRole;admin?:boolean}) {
 const [query,setQuery]=useState(''),[role,setRole]=useState<HelpRole>(initialRole),[playing,setPlaying]=useState<string|null>(null);
 const guides=filterGuides(query,role),tutorials=helpTutorials.filter(t=>role==='ALL'||t.roles.includes(role));
 useEffect(()=>{const open=()=>{const node=document.getElementById(window.location.hash.slice(1));if(node instanceof HTMLDetailsElement){node.open=true;node.scrollIntoView({block:'start'});}};open();window.addEventListener('hashchange',open);return()=>window.removeEventListener('hashchange',open);},[guides.map(g=>g.id).join(',')]);
 function showGuide(id:string){setQuery('');if(role==='ADMIN')setRole('ALL');window.setTimeout(()=>{const el=document.getElementById('guide-'+id);if(el instanceof HTMLDetailsElement){el.open=true;el.scrollIntoView({block:'start'});el.querySelector('summary')?.focus();}},0);}
 return <section aria-labelledby="help-guides" className={s.section}>
  <div><h2 id="help-guides">Un coup de main, à chaque étape</h2><p className={s.intro}>Retrouvez une explication, regardez un tutoriel ou contactez le support. Guides mis à jour le 20 septembre 2026.</p>{!admin&&<p><a href="#help-videos">Voir les tutoriels vidéo</a> · <a href="#support">Contacter le support</a></p>}</div>
  <nav className={s.shortcuts} aria-label="Questions fréquentes"><a className={s.shortcut} href="#guide-pdf-manquant" onClick={()=>showGuide('pdf-manquant')}>Mon PDF manque</a><a className={s.shortcut} href="#guide-email-manquant" onClick={()=>showGuide('email-manquant')}>Je ne reçois pas l’email</a><a className={s.shortcut} href="#guide-matching-incomplet" onClick={()=>showGuide('matching-incomplet')}>Mon matching est incomplet</a></nav>
  <div className={s.filters}><TextField label="Rechercher dans l’aide" type="search" value={query} maxLength={150} onChange={e=>setQuery(e.target.value)}/><SelectField label="Votre espace" value={role} onChange={e=>{setRole(e.target.value as HelpRole);setPlaying(null);}}><option value="ALL">Tous les espaces</option><option value="NURSE">Intérimaire</option><option value="ESTABLISHMENT">Établissement</option><option value="AGENCY">Agence</option><option value="ADMIN">Administrateur</option></SelectField></div>
  {!admin&&<section aria-labelledby="help-videos"><h2 id="help-videos">Tutoriels vidéo</h2><p className={s.intro}>Des parcours filmés dans InfiMatch avec des données fictives. Les réponses sont simulées pour la démonstration : aucune mission réelle ni aucun email réel n’est créé. Choisissez un tutoriel pour charger la vidéo.</p>
   <div className={s.grid}>{tutorials.map(t=><article className={s.card} key={t.id}><h3>{t.title}</h3><p>{t.summary}</p>{t.media.kind==='external'?<a className={s.external} href={t.media.url} target="_blank" rel="noopener noreferrer">Regarder la vidéo — site externe</a>:<><button type="button" aria-expanded={playing===t.id} aria-controls={'video-'+t.id} onClick={()=>setPlaying(playing===t.id?null:t.id)}>{playing===t.id?'Fermer la vidéo':'Voir le tutoriel'}<span className={s.srOnly}> : {t.title}</span></button><div id={'video-'+t.id} hidden={playing!==t.id}>{playing===t.id&&<video controls playsInline preload="none" poster={t.media.poster} aria-label={t.title}><source src={t.media.src} type="video/webm"/><track kind="captions" src={t.media.captions} srcLang="fr" label="Français"/>Votre navigateur ne peut pas lire cette vidéo.</video>}</div></>}<details><summary>Les étapes par écrit</summary><ol>{t.steps.map(step=><li key={step}>{step}</li>)}</ol></details></article>)}</div>
   {!tutorials.length&&<p>Les tutoriels métier sont disponibles en choisissant un autre espace. Les guides administrateur sont proposés ci-dessous.</p>}
  </section>}
  <section aria-labelledby="written-guides"><h2 id="written-guides">Guides et réponses</h2><p role="status">{guides.length} guide(s)</p>{guides.map(g=><details className={s.guide} id={'guide-'+g.id} key={g.id}><summary>{g.title}</summary><ol>{g.steps.map((step,i)=><li key={i}>{step}</li>)}</ol>{g.href&&!admin&&<Link to={g.href}>{g.label}</Link>}</details>)}{!guides.length&&<p>Aucun guide trouvé. Essayez un autre terme ou contactez le support.</p>}</section>
 </section>;
}
