import {useEffect,useRef,useState,type FormEvent} from 'react';
import {Button} from '@/ui/Button';
import {TextField,SelectField,TextArea} from '@/ui/Field';
export type SupportRequest=<T>(path:string,body?:unknown)=>Promise<T>;
type Ticket={id:string;category:string;subject:string;description?:string;status:string;created_at:string;updated_at:string};
type Reply={id:string;body:string;is_staff:boolean;created_at:string};
const categories={ACCESS:'Accès au compte',PROFILE:'Profil et qualifications',MISSION:'Mission et affectation',DOCUMENT:'Documents',NOTIFICATION:'Notifications et emails',OTHER:'Autre question'};
const date=(v:string)=>new Date(v).toLocaleString('fr-FR',{timeZone:'Europe/Paris'});
export function SupportTickets({request,staff=false,initialTicket=''}:{request:SupportRequest;staff?:boolean;initialTicket?:string}){
 const [list,setList]=useState<{items:Ticket[];hasMore:boolean}|null>(null),[offset,setOffset]=useState(0),[version,setVersion]=useState(0),[selected,setSelected]=useState(initialTicket),[replyOffset,setReplyOffset]=useState(0),[detail,setDetail]=useState<{ticket:Ticket;replies:Reply[];hasMore:boolean}|null>(null);
 const [error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[category,setCategory]=useState('OTHER'),[subject,setSubject]=useState(''),[description,setDescription]=useState(''),[reply,setReply]=useState(''),[resolve,setResolve]=useState(false),[reauth,setReauth]=useState(false),[password,setPassword]=useState('');
 const createKey=useRef(crypto.randomUUID()),replyKey=useRef(crypto.randomUUID());
 useEffect(()=>{let live=true;setList(null);request<{items:Ticket[];hasMore:boolean}>('/support-tickets?offset='+offset).then(d=>{if(live)setList(d);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[request,offset,version]);
 useEffect(()=>{let live=true;setDetail(null);if(selected)request<{ticket:Ticket;replies:Reply[];hasMore:boolean}>('/support-tickets/'+encodeURIComponent(selected)+'?offset='+replyOffset).then(d=>{if(live)setDetail(d);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[request,selected,replyOffset,version]);
 function pick(id:string){setSelected(id);setReplyOffset(0);setError('');setMessage('');setReply('');setResolve(false);replyKey.current=crypto.randomUUID();}
 async function create(e:FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');try{const r=await request<{id:string}>('/support-tickets',{clientRequestId:createKey.current,category,subject,description});createKey.current=crypto.randomUUID();setSubject('');setDescription('');pick(r.id);setMessage('Votre demande est enregistrée. Référence : '+r.id+'. Retrouvez les réponses ici et dans vos notifications.');setOffset(0);setVersion(v=>v+1);}catch(e){setError(e instanceof Error?e.message:'Enregistrement impossible.');}finally{setBusy(false);}}
 async function respond(e:FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');try{if(reauth){await request('/reauth',{password});setPassword('');setReauth(false);}await request('/support-tickets/'+selected+'/replies',{clientRequestId:replyKey.current,body:reply,...(staff?{status:resolve?'RESOLVED':'OPEN'}:{})});replyKey.current=crypto.randomUUID();setReply('');setReplyOffset(0);setVersion(v=>v+1);setMessage('Votre réponse est enregistrée.');}catch(e){if((e as {code?:string}).code==='ADMIN_REAUTH_REQUIRED')setReauth(true);setError(e instanceof Error?e.message:'Réponse impossible.');}finally{setBusy(false);}}
 return <section aria-labelledby="support-requests" style={{display:'grid',gridTemplateColumns:'minmax(0,1fr)',gap:16,overflowWrap:'anywhere'}}><h2 id="support-requests">{staff?'Demandes reçues':'Mes demandes de support'}</h2><p>Indiquez le problème et, si utile, la référence de mission. N’ajoutez ni mot de passe, ni RIB, ni document d’identité, ni information concernant un patient. Aucune pièce jointe n’est acceptée ici.</p>
 {error&&<div role="alert"><p>{error}</p><Button type="button" variant="outline" onClick={()=>{setError('');setVersion(v=>v+1);}}>Réessayer le chargement</Button></div>}{message&&<p role="status">{message}</p>}
 {!staff&&<details><summary>Ouvrir une nouvelle demande</summary><form onSubmit={create} style={{display:'grid',gap:12,paddingBlock:16}}><SelectField label="Catégorie" value={category} onChange={e=>setCategory(e.target.value)}>{Object.entries(categories).map(([value,label])=><option key={value} value={value}>{label}</option>)}</SelectField><TextField label="Sujet" required minLength={3} maxLength={150} value={subject} onChange={e=>setSubject(e.target.value)}/><TextArea label="Description du problème" required minLength={10} maxLength={4000} value={description} onChange={e=>setDescription(e.target.value)}/><Button type="submit" disabled={busy}>Envoyer ma demande</Button></form></details>}
 {!list&&!error&&<p role="status">Chargement des demandes…</p>}{list&&<><ul style={{paddingInlineStart:20}}>{list.items.map(t=><li key={t.id} style={{marginBlock:12}}><button type="button" onClick={()=>pick(t.id)} style={{textAlign:'left',whiteSpace:'normal',overflowWrap:'anywhere',maxWidth:'100%'}}>{t.subject}</button> — {t.status==='RESOLVED'?'Résolue':'Ouverte'}<br/><small>Référence {t.id} · {date(t.updated_at)}</small></li>)}</ul>{!list.items.length&&<p>Aucune demande sur cette page.</p>}<div style={{display:'flex',gap:12,flexWrap:'wrap'}}><Button type="button" variant="outline" disabled={!offset} onClick={()=>setOffset(v=>Math.max(0,v-20))}>Demandes précédentes</Button><Button type="button" variant="outline" disabled={!list.hasMore} onClick={()=>setOffset(v=>v+20)}>Demandes suivantes</Button></div></>}
 {detail&&<article style={{border:'1px solid var(--line)',padding:16,borderRadius:12,minWidth:0}}><h3>{detail.ticket.subject}</h3><p>Référence : {detail.ticket.id}</p><p>{categories[detail.ticket.category as keyof typeof categories]} · {detail.ticket.status==='RESOLVED'?'Résolue':'Ouverte'} · {date(detail.ticket.created_at)}</p><p style={{whiteSpace:'pre-wrap'}}>{detail.ticket.description}</p><h4>Échanges</h4>{detail.replies.map(r=><div key={r.id} style={{paddingBlock:10,borderTop:'1px solid var(--line)'}}><p><strong>{r.is_staff?'Équipe support':'Demandeur'}</strong> · {date(r.created_at)}</p><p style={{whiteSpace:'pre-wrap'}}>{r.body}</p></div>)}{!detail.replies.length&&<p>Votre demande est enregistrée. Aucune réponse pour le moment.</p>}<div style={{display:'flex',gap:12,flexWrap:'wrap'}}><Button type="button" variant="ghost" disabled={!replyOffset} onClick={()=>setReplyOffset(v=>Math.max(0,v-20))}>Réponses précédentes</Button><Button type="button" variant="ghost" disabled={!detail.hasMore} onClick={()=>setReplyOffset(v=>v+20)}>Réponses suivantes</Button></div><form onSubmit={respond} style={{display:'grid',gap:12}}><TextArea label="Ajouter une réponse" required minLength={2} maxLength={4000} value={reply} onChange={e=>setReply(e.target.value)}/>{staff&&<label><input type="checkbox" checked={resolve} onChange={e=>setResolve(e.target.checked)}/> Marquer la demande résolue après cette réponse</label>}{reauth&&<TextField type="password" label="Confirmer votre mot de passe administrateur" required autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/>}<Button type="submit" disabled={busy}>Enregistrer la réponse</Button></form></article>}
 </section>;
}
