import {spawnSync} from 'node:child_process';import {readFile,writeFile,mkdir,cp} from 'node:fs/promises';import {resolve,join} from 'node:path';import {randomBytes,createHash} from 'node:crypto';import {parse} from 'dotenv';
const root=resolve(import.meta.dirname,'../..'),folder=resolve(process.argv[2]||'');if(!folder.startsWith(resolve(root,'backups')+ (process.platform==='win32'?'\\':'/')))throw Error('Select a backup inside project backups');
const proof=resolve(root,'docs/proofs/v1-hardening');await mkdir(proof,{recursive:true});await mkdir(join(root,'data/security'),{recursive:true});const manifest=JSON.parse(await readFile(join(folder,'manifest.json'),'utf8'));const checks=[];
for(const f of manifest.files){const bytes=await readFile(join(folder,f.path));if(createHash('sha256').update(bytes).digest('hex')!==f.sha256)throw Error('Backup checksum mismatch');}checks.push('all backup file checksums');
const id='infimatch-restore-'+Date.now(),pass=randomBytes(24).toString('hex'),containers=[];
function docker(args,input){const r=spawnSync('docker',args,{input,maxBuffer:512*1024*1024});if(r.status!==0)throw Error('Restore command failed: '+r.stderr.toString().slice(-1000));return r.stdout;}
async function wait(args){for(let i=0;i<60;i++){try{return docker(args);}catch{}await new Promise(r=>setTimeout(r,500));}throw Error('Restore service timeout');}
try{
 await writeFile(join(proof,'restore.json'),JSON.stringify({date:new Date().toISOString(),status:'RUNNING'}));
 const pg=id+'-pg';containers.push(pg);docker(['run','-d','--name',pg,'-e','POSTGRES_USER=restore_admin','-e','POSTGRES_PASSWORD='+pass,'-e','POSTGRES_DB=postgres','-p','127.0.0.1:55434:5432','--tmpfs','/var/lib/postgresql/data','postgis/postgis:17-3.5@sha256:01a6a70e41e6c4467c8f55f6063555ed72db2d6662cd0d571040d42eadaeb6f6']);await wait(['exec',pg,'pg_isready','-h','127.0.0.1','-U','restore_admin','-d','postgres']);docker(['exec',pg,'createdb','-U','restore_admin','-T','template0','infimatch_restore']);if(manifest.files.some(f=>f.path==='postgres-roles.sql'))docker(['exec','-i',pg,'psql','-v','ON_ERROR_STOP=1','-U','restore_admin','-d','postgres'],await readFile(join(folder,'postgres-roles.sql')));
 docker(['exec','-i',pg,'pg_restore','-U','restore_admin','-d','infimatch_restore',...(manifest.files.some(f=>f.path==='postgres-roles.sql')?[]:['--no-owner','--no-privileges'])],await readFile(join(folder,'postgres.dump')));
 const query='SELECT json_build_object(\'accounts\',(SELECT count(*) FROM account),\'missions\',(SELECT count(*) FROM mission),\'assignments\',(SELECT count(*) FROM assignment),\'documents\',(SELECT count(*) FROM document))';const before=manifest.sqlCounts;const after=JSON.parse(docker(['exec',pg,'psql','-U','restore_admin','-d','infimatch_restore','-Atc',query]).toString());if(before&&Object.keys(after).some(k=>before[k]!==after[k]))throw Error('Restored SQL counts differ from backup manifest');checks.push(before?'PostgreSQL restore and snapshot row counts':'PostgreSQL restore; legacy manifest has no reference counts');if(process.argv.includes('--require-representative')&&(after.missions<1||after.assignments<1||after.documents<1))throw Error('Backup is not representative: need at least one mission, assignment and document');checks.push(after.missions>=1&&after.assignments>=1&&after.documents>=1?'representative missions and documents':'empty business set recorded');
 const migration=spawnSync(process.execPath,['backend/dist/cli.js','migrate'],{cwd:root,env:{...process.env,INFIMATCH_SECRET_SOURCE:'vault',DATABASE_URL:`postgresql://restore_admin:${pass}@127.0.0.1:55434/infimatch_restore`},encoding:'utf8'});if(migration.status!==0)throw Error('Restored database migration failed '+migration.stderr);checks.push('security migrations on restored existing database');
 const mongo=id+'-mongo';containers.push(mongo);docker(['run','-d','--name',mongo,'-p','127.0.0.1:57019:27017','--tmpfs','/data/db','mongo:8.0.5@sha256:7bd28e5eea1c5766a084d5818254046f3ebe3b8f20a65e3a274640189e296667']);await wait(['exec',mongo,'mongosh','--quiet','--eval',"db.adminCommand('ping')"]);docker(['exec','-i',mongo,'mongorestore','--archive','--gzip','--nsExclude=admin.*','--nsExclude=config.*','--nsExclude=local.*'],await readFile(join(folder,'mongo.archive.gz')));checks.push('MongoDB archive restored');
 const old=parse(await readFile(join(folder,'legacy.env'),'utf8'));const {decrypt}=await import('../../backend/dist/documents/crypto.js');const docs=JSON.parse(docker(['exec',pg,'psql','-U','restore_admin','-d','infimatch_restore','-Atc',"SELECT coalesce(json_agg(d),'[]') FROM (SELECT id::text,key_version,size_bytes FROM document) d"]).toString());let documents=0;for(const row of docs){if(!/^[0-9a-f-]{36}$/i.test(row.id))throw Error('Invalid restored document identifier');const v=row.key_version,key=v===Number(old.DOCUMENT_KEY_VERSION||1)?old.DOCUMENT_KEY:old['DOCUMENT_KEY_V'+v];if(!key)throw Error('Missing document key for restored file '+row.id);const clear=decrypt(await readFile(join(folder,'documents',row.id+'.bin')),Buffer.from(key,'base64'),row.id);if(clear.length!==row.size_bytes)throw Error('Restored document size mismatch');documents++;}if(docs.length!==documents)throw Error('Restored documents missing or undecryptable');checks.push('restored document decryption: '+documents);
 const n8n=id+'-n8n';containers.push(n8n);docker(['run','-d','--name',n8n,'--entrypoint','sh','docker.n8n.io/n8nio/n8n:2.38.7@sha256:a8c95f75c6fdf65f5f2b7a7b354744eaa1c62bb911b5c00af6499c3f38e4cd32','-c','sleep 600']);docker(['exec','-i',n8n,'sh','-c','tar -C /home/node/.n8n -xf -'],await readFile(join(folder,'n8n.tar')));docker(['exec',n8n,'n8n','export:workflow','--all','--output=/tmp/restored-workflows.json']);const flows=JSON.parse(docker(['exec',n8n,'cat','/tmp/restored-workflows.json']).toString());if(flows.length<3)throw Error('Missing restored workflows');checks.push('n8n SQLite restored and three workflows exported');
 const vault=id+'-vault';containers.push(vault);const config=join(root,'data/security',id+'-vault.hcl');await writeFile(config,'storage "raft" { path = "/vault/file" }\nlistener "tcp" { address = "0.0.0.0:8200" tls_disable = true }\napi_addr = "http://127.0.0.1:8200"\ncluster_addr = "http://127.0.0.1:8201"\ndisable_mlock = true\n');docker(['run','-d','--name',vault,'-e','VAULT_ADDR=http://127.0.0.1:8200','-v',config+':/vault/config/restore.hcl:ro','--entrypoint','vault','hashicorp/vault:2.1@sha256:5520cc26271c024e6ffa45cdf95255bd26b70d71ba4b7e0bc18925bef4128adb','server','-config=/vault/config/restore.hcl']);
 let init;for(let i=0;i<30;i++){try{init=JSON.parse(docker(['exec',vault,'vault','operator','init','-key-shares=1','-key-threshold=1','-format=json']).toString());break;}catch{}await new Promise(r=>setTimeout(r,500));}if(!init)throw Error('Vault restore initialization failed');docker(['exec',vault,'vault','operator','unseal',init.unseal_keys_b64[0]]);docker(['cp',join(folder,'vault.snap'),vault+':/tmp/vault.snap']);docker(['exec','-e','VAULT_TOKEN='+init.root_token,vault,'vault','operator','raft','snapshot','restore','-force','/tmp/vault.snap']);await new Promise(r=>setTimeout(r,1500));
 const recovery=JSON.parse(await readFile(join(folder,'vault-private/recovery.json'),'utf8'));for(const key of recovery.keys_base64.slice(0,recovery.threshold||2))docker(['exec',vault,'vault','operator','unseal',key]);
 const creds=JSON.parse(await readFile(join(folder,'vault-private/backend.json'),'utf8'));const login=JSON.parse(docker(['exec',vault,'vault','write','-format=json','auth/approle/login','role_id='+creds.role_id,'secret_id='+creds.secret_id]).toString());const value=JSON.parse(docker(['exec','-e','VAULT_TOKEN='+login.auth.client_token,vault,'vault','kv','get','-format=json','kv/infimatch/v1/backend']).toString());if(value.data.data.DOCUMENT_KEY!==old.DOCUMENT_KEY)throw Error('Restored Vault key differs');checks.push('Vault Raft restored, original unseal keys and backend AppRole verified');
 const ledger=join(root,'data/privacy/erasure-ledger.ndjson');
 const ledgerPresent=await readFile(ledger,'utf8').then(()=>true,e=>{if(e.code==='ENOENT')return false;throw e;});
 if(ledgerPresent){
  const workDocuments=join(root,'data/security',id+'-documents');await cp(join(folder,'documents'),workDocuments,{recursive:true});
  const replay=spawnSync(process.execPath,['backend/dist/cli.js','replay-erasures','--ledger',ledger],{cwd:root,env:{...process.env,...old,INFIMATCH_SECRET_SOURCE:'vault',DATABASE_URL:`postgresql://restore_admin:${pass}@127.0.0.1:55434/infimatch_restore`,MONGODB_URI:'mongodb://127.0.0.1:57019/infimatch',DOCUMENT_DIRECTORY:workDocuments},encoding:'utf8'});
  if(replay.status!==0)throw Error('Erasure replay failed; restored service must remain offline');checks.push('current erasure ledger replayed on restored databases');
 }else checks.push('no current erasure ledger; operator must confirm there are no later erasures before reopening');
 await writeFile(join(proof,'restore.json'),JSON.stringify({date:new Date().toISOString(),status:'PASS',checks,sqlCounts:after,representative:after.missions>=1&&after.assignments>=1&&after.documents>=1},null,2));console.log(JSON.stringify({status:'PASS',checks,representative:after.missions>=1&&after.assignments>=1&&after.documents>=1}));
}catch(e){await writeFile(join(proof,'restore.json'),JSON.stringify({date:new Date().toISOString(),status:'FAIL',checks},null,2));throw e;}finally{for(const name of containers.reverse())docker(['rm','-f','-v',name]);}
