import 'reflect-metadata';
import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {Database} from '../../src/database/database';
import {SupportService} from '../../src/support/support.service';
import {anonymizeAccount} from '../../src/security/retention';
let db:Database,service:SupportService;
before(async()=>{const u=new URL(process.env.DATABASE_URL||'http://invalid');if(process.env.NODE_ENV!=='test'||u.hostname!=='127.0.0.1'||u.port!=='55433'||u.pathname!=='/infimatch_test')throw Error('Requires isolated database');db=await new Database().connect();await db.source.runMigrations({transaction:'all'});service=new SupportService(db);});
after(async()=>{await db?.onModuleDestroy();});
async function account(){return (await db.query("INSERT INTO account(email,password_hash,family,terms_version) VALUES($1,'fixture','NURSE','fixture') RETURNING id",[randomUUID()+'@example.invalid']))[0].id as string;}
const input=()=>({clientRequestId:randomUUID(),category:'MISSION',subject:'Mission fictive',description:'Description fictive sans données personnelles.'});
test('support enforces ownership for detail and reply and rejects cross-account discovery',async()=>{const owner=await account(),other=await account(),t=await service.create(owner,input());assert.equal((await service.list(other,0)).items.length,0);await assert.rejects(service.detail(other,t.id,0),e=>(e as any).status===404);await assert.rejects(service.reply(other,t.id,{clientRequestId:randomUUID(),body:'Intrusion'}),e=>(e as any).status===404);assert.equal((await service.detail(owner,t.id,0)).ticket.id,t.id);});
test('support serializes concurrent creation, acknowledges once, and rejects key payload replacement',async()=>{const owner=await account(),b=input();const [a,c]=await Promise.all([service.create(owner,b),service.create(owner,b)]);assert.equal(a.id,c.id);assert.equal((await db.query("SELECT id FROM notification WHERE user_id=$1 AND kind='SUPPORT_RECEIVED'",[owner])).length,1);await assert.rejects(service.create(owner,{...b,description:'Une autre description non identique.'}),e=>(e as any).status===409);});
test('support limits creation and pages results, preserving text without interpretation',async()=>{const owner=await account();for(let n=0;n<5;n++)await service.create(owner,{...input(),description:'<script>alert("fictif")</script>'});await assert.rejects(service.create(owner,input()),e=>(e as any).status===429);const list=await service.list(owner,0);assert.equal(list.items.length,5);assert.equal(list.hasMore,false);assert.equal((await service.list(owner,20)).items.length,0);assert.equal((await service.detail(owner,list.items[0].id,0)).ticket.description,'<script>alert("fictif")</script>');});
test('staff response is idempotent, notifies once, and client follow-up reopens resolved ticket',async()=>{const owner=await account(),staff=await account(),t=await service.create(owner,input()),b={clientRequestId:randomUUID(),body:'Réponse fictive',status:'RESOLVED'};await service.reply(staff,t.id,b,true);await service.reply(staff,t.id,b,true);assert.equal((await service.detail(owner,t.id,0)).ticket.status,'RESOLVED');assert.equal((await db.query("SELECT id FROM notification WHERE user_id=$1 AND kind='SUPPORT_REPLY'",[owner])).length,1);await service.reply(owner,t.id,{clientRequestId:randomUUID(),body:'Complément fictif'});const d=await service.detail(owner,t.id,0);assert.equal(d.ticket.status,'OPEN');assert.equal(d.replies.length,2);assert.equal(d.replies[0].is_staff,true);});
test('account closure removes owned tickets including staff text and scrubs authored replies elsewhere',async()=>{const owner=await account(),other=await account(),t=await service.create(owner,input()),second=await service.create(other,input());await service.reply(other,t.id,{clientRequestId:randomUUID(),body:'Réponse staff sur le dossier clos'},true);await service.reply(owner,second.id,{clientRequestId:randomUUID(),body:'Texte personnel de support'},true);await db.transaction(em=>anonymizeAccount(em,owner));assert.equal((await db.query('SELECT id FROM support_ticket WHERE id=$1',[t.id])).length,0);assert.equal((await db.query('SELECT id FROM support_reply WHERE ticket_id=$1',[t.id])).length,0);const [r]=await db.query('SELECT body,author_id FROM support_reply WHERE ticket_id=$1',[second.id]);assert.equal(r.author_id,null);assert.equal(r.body,'Message supprimé après clôture du compte.');await assert.rejects(service.create(owner,input()),e=>(e as any).status===404);});
