import 'reflect-metadata';
import {test} from 'node:test';
import assert from 'node:assert/strict';
import {plainToInstance} from 'class-transformer';
import {validateSync} from 'class-validator';
import {DocumentsController,DocumentsService,CvUploadDto} from '../../src/documents/documents.module';
import {Database} from '../../src/database/database';
import {cvFileMime,DOCX_MIME} from '../../src/documents/cv-file';
const pdf=Buffer.from('%PDF-1.4\nfixture');
function zip(names:string[]){let offset=0;const locals:Buffer[]=[],central:Buffer[]=[];for(const name of names){const n=Buffer.from(name),l=Buffer.alloc(30),c=Buffer.alloc(46);l.writeUInt32LE(0x04034b50);l.writeUInt16LE(n.length,26);c.writeUInt32LE(0x02014b50);c.writeUInt16LE(n.length,28);c.writeUInt32LE(offset,42);locals.push(l,n);central.push(c,n);offset+=30+n.length;}const dir=Buffer.concat(central),end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50);end.writeUInt16LE(names.length,8);end.writeUInt16LE(names.length,10);end.writeUInt32LE(dir.length,12);end.writeUInt32LE(offset,16);return Buffer.concat([...locals,dir,end]);}
test('CV DTO requires explicit storage and bounds content',()=>{const errors=(value:any)=>validateSync(plainToInstance(CvUploadDto,value),{whitelist:true,forbidNonWhitelisted:true});assert.equal(errors({mime:'application/pdf',contentBase64:pdf.toString('base64'),reviewed:true}).length,0);for(const extra of [{reviewed:false},{mime:'text/html'},{owner_id:'other'},{contentBase64:'x'.repeat(4200001)}])assert.ok(errors({mime:'application/pdf',contentBase64:pdf.toString('base64'),reviewed:true,...extra}).length);});
test('CV storage validates signatures including bounded DOCX package',()=>{assert.equal(cvFileMime(pdf),'application/pdf');assert.equal(cvFileMime(zip(['[Content_Types].xml','word/document.xml'])),DOCX_MIME);for(const bytes of [Buffer.from('not a document'),zip(['random.txt']),zip(['[Content_Types].xml','word/document.xml','word/vbaProject.bin']),zip(['[Content_Types].xml','word/document.xml']).subarray(0,40)])assert.equal(cvFileMime(bytes),null);});
test('CV upload uses authenticated nurse, private storage, original bytes and idempotent command',async()=>{let allowed=true;const stores:any[][]=[];const db={transaction:async(fn:any)=>fn({query:async()=>allowed?[{user_id:'owner'}]:[]})} as unknown as Database;const documents={store:async(...args:any[])=>{stores.push(args);return {id:'saved',status:'READY'};}} as unknown as DocumentsService;const c=new DocumentsController(db,documents);const body={mime:'application/pdf',contentBase64:pdf.toString('base64'),reviewed:true};assert.deepEqual(await c.uploadCv({session:{userId:'owner'}} as any,'retry-key',body),{id:'saved',status:'READY'});assert.equal(stores[0]![0],'owner');assert.equal(stores[0]![1],'CV');assert.deepEqual(stores[0]![3],pdf);assert.equal(stores[0]![5].key,'retry-key');for(const b of [{...body,reviewed:false},{...body,mime:'image/png'},{...body,contentBase64:Buffer.alloc(3*1024*1024+1).toString('base64')}])await assert.rejects(c.uploadCv({session:{userId:'owner'}} as any,'key',b));allowed=false;await assert.rejects(c.uploadCv({session:{userId:'other'}} as any,'key',body));assert.equal(stores.length,1);});
