const str={type:"string"},num={type:"number"},int={type:"integer"},bool={type:"boolean"},uuid={...str,format:"uuid"},date={...str,format:"date-time"};
const obj=(properties:Record<string,any>,required:string[]=[])=>({type:"object",properties,required});
const array=(items:any)=>({type:"array",items});const nullable=(s:any)=>({...s,nullable:true});const ref=(s:string)=>({$ref:"#/components/schemas/"+s});
const page=(items:any)=>obj({items:array(items),limit:int,offset:int,total:int,excluded:int},["items","limit","offset","total"]);
const interval=obj({start:date,end:date},["start","end"]);
const organization=obj({id:uuid,kind:{...str,enum:["AGENCY","ESTABLISHMENT"]},name:str,address:str,referent:str,finess:nullable(str),siret:nullable(str)},["id","kind","name"]);
const session=obj({idleTimeoutMs:int,idleExpiresAt:int},["idleTimeoutMs","idleExpiresAt"]);
const match=obj({eligible:bool,score:nullable(num),reasons:array(str),missionId:uuid,explanationId:nullable(str),historyStatus:str,candidateId:uuid,display_name:str,qualifications:array(str),skills:array(str)},["eligible","score"]);
const closure=obj({id:uuid,status:{...str,enum:["REQUESTED","APPROVED","PROCESSING","COMPLETED","CANCELLED","REJECTED"]},requested_at:date,approved_at:nullable(date),completed_at:nullable(date),decision_reason:nullable(str),last_error:nullable(str)},["id","status","requested_at"]);
const profile=obj({user_id:uuid,display_name:str,qualifications:array(str),skills:array(str),experience:array(obj({service:str,months:num})),available:array(interval),unavailable:array(interval),latitude:nullable(num),longitude:nullable(num),radius_km:nullable(num),accepted_shifts:array(str),preferred_shifts:array(str),visible:bool,notifications_enabled:bool,rpps_number:nullable(str),rpps_status:{...str,enum:["NOT_CHECKED","FOUND","NOT_FOUND","PENDING"]},rpps_version:int,rpps_checked_at:nullable(date),updated_at:date,details:{type:"object",additionalProperties:true,description:"Versioned professional form fields; no bank document or credential"}},["user_id","display_name","qualifications","available","unavailable","rpps_status"]);
const auth=obj({user:obj({id:uuid,family:{...str,enum:["NURSE","ENTERPRISE"]}},["id","family"]),csrfToken:str},["user","csrfToken"]);
const ok=obj({ok:{type:"boolean",enum:[true]}},["ok"]);
const finess=obj({finess:str,name:str,address:str,city:str,postal_code:str,category_code:str,category_label:str},["finess","name"]);
export const additionalSchemas={Profile:profile,Organization:organization,SessionTiming:session,AuthReceipt:auth,MatchResult:match,ClosureRequest:closure,
 OfferFreshness:obj({lastSeenAt:nullable(date),staleAfterDays:int,state:{...str,enum:["RECENTLY_SEEN","STALE_UNVERIFIED","EXPIRED"]}},["lastSeenAt","staleAfterDays","state"]),
 ExternalCorrespondence:obj({mode:str,score:nullable(num),eligibilityVerified:bool,criteria:{type:"object",additionalProperties:obj({status:str,reason:str,offerValue:{},profileValue:{},value:{}})},warnings:array(str),missingForFullMatching:array(str)}),
};
export const additionalResponses:Record<string,any>={
 "GET /api/v1/listings/locations":obj({provider:str,items:array(obj({label:str,latitude:num,longitude:num}))}),

 "PUT /api/v1/me/bank-document":obj({id:uuid,status:str}),
 "GET /api/v1/me/bank-document":{type:'string',format:'binary'},

 "POST /api/v1/auth/recovery/request":obj({ok:bool,message:str}),
 "POST /api/v1/auth/recovery/complete":ok,
 "GET /api/v1/admin/recovery-requests":page(obj({id:uuid,account_id:uuid,email:str,status:str,requested_at:date,issued_at:nullable(date),expires_at:nullable(date),completed_at:nullable(date),decision_reason:nullable(str)})),
 "POST /api/v1/admin/recovery-requests/{id}/issue":obj({id:uuid,status:str,resetUrl:str,expiresAt:date}),
 "POST /api/v1/admin/recovery-requests/{id}/reject":ok,
 "GET /api/v1/admin/privacy-requests/{id}":obj({request:closure,blockers:array(obj({code:str,label:str})),canExecute:bool}),
 "POST /api/v1/admin/privacy-requests/{id}/approve":ok,
 "POST /api/v1/admin/privacy-requests/{id}/reject":ok,
 "POST /api/v1/admin/privacy-requests/{id}/execute":obj({ok:bool,status:str,last_error:nullable(str)}),

 "GET /api/v1/admin/csrf":obj({csrfToken:str}),
 "GET /api/v1/admin/accounts/{id}/notifications":obj({observedAt:str,connection:obj({}),personal:obj({}),internal:obj({}),deliveries:obj({}),organizations:array(obj({})),catalog:obj({})}),
 "POST /api/v1/admin/login":obj({status:str,csrfToken:str,role:str}),
 "POST /api/v1/admin/activate":obj({status:str,csrfToken:str,role:str}),
 "POST /api/v1/admin/reauth":ok,"POST /api/v1/admin/logout":ok,
 "GET /api/v1/admin/me":obj({id:uuid,email:str,role:str,permissions:array(str),mfaAt:num}),
 "GET /api/v1/admin/overview":obj({observedAt:date,counts:obj({accounts:int,organizations:int,applications:int,pendingEvents:int,failedEvents:int,documents:int,missions:{type:"object",additionalProperties:int}}),alerts:array(obj({kind:str,message:str,href:str}))}),
 "GET /api/v1/admin/accounts":page(obj({id:uuid,email:str,family:str,active:bool,created_at:date,organizations:array(organization),rpps_status:str,rpps_checked_at:nullable(date)})),
 "GET /api/v1/admin/accounts/{id}":obj({account:obj({id:uuid,email:str,family:str,active:bool,created_at:date}),profile:nullable(obj({display_name:str,qualifications:array(str),rpps_status:str})),organizations:array(organization),documents:array(obj({id:uuid,kind:str,mime:str,status:str,size_bytes:int,created_at:date})),audit:array(obj({event:str,created_at:date}))}),
 "POST /api/v1/admin/accounts/{id}/state":ok,"POST /api/v1/admin/accounts/{id}/revoke":ok,
 "GET /api/v1/admin/organizations":page(organization),
 "GET /api/v1/admin/organizations/{id}":obj({organization,members:array(obj({user_id:uuid,email:str,active:bool,account_active:bool})),links:array(obj({agency_id:uuid,establishment_id:uuid,agency_name:str,establishment_name:str}))}),
 "POST /api/v1/admin/organizations/{id}/members":ok,"POST /api/v1/admin/organizations/{id}/links":ok,
 "GET /api/v1/admin/missions/{id}/matching":page(obj({id:str,ownerId:uuid,missionId:uuid,missionVersion:int,profileVersion:str,rulesVersion:str,createdAt:date,expiresAt:date,result:match,stale:bool})),
 "GET /api/v1/admin/accounts/{id}/verification":obj({directory:obj({status:str,checkedAt:nullable(date),reason:nullable(str),identityReview:str}),professionalIdentity:nullable(obj({issuer:str,authenticatedAt:date})),reviews:array(obj({id:uuid,state:str,reason:str,created_at:date,actor_id:uuid}))}),
 "POST /api/v1/admin/accounts/{id}/verification":ok,
 "GET /api/v1/admin/operations":obj({sources:array(obj({provider:str,enabled:bool,updated_at:date,nextScheduleLabel:str,counts:obj({total:int,active:int}),lastRun:nullable(obj({status:str,created_at:date,accepted:nullable(int),rejected:nullable(int),duplicates:nullable(int),error:nullable(str)}))})),incidents:array(obj({id:uuid,service:str,state:str,impact:str,owner_label:str,started_at:date,updated_at:date,resolved_at:nullable(date)})),observedAt:date}),
 "POST /api/v1/admin/operations/sources/{provider}/state":ok,
 "POST /api/v1/admin/operations/sources/{provider}/refresh":obj({provider:str,status:str,accepted:int}),
 "GET /api/v1/admin/incidents":page(obj({id:uuid,service:str,state:str,impact:str,owner_label:str,started_at:date,updated_at:date,resolved_at:nullable(date)})),
 "POST /api/v1/admin/incidents":obj({id:uuid}),"POST /api/v1/admin/incidents/{id}":ok,
 "GET /api/v1/admin/privacy-requests":page(obj({id:uuid,account_id:uuid,status:str,requested_at:date,approved_at:nullable(date),completed_at:nullable(date)})),

 "GET /api/v1/admin/missions":page(ref("Mission")),
 "GET /api/v1/admin/missions/{id}":obj({mission:ref("Mission"),applications:array(ref("Application")),assignments:array(ref("Assignment")),events:array(obj({event:str,created_at:date,actor_id:nullable(uuid)}))}),
 "GET /api/v1/admin/jobs":page(obj({id:uuid,event:str,attempts:int,created_at:date,available_at:date,completed_at:nullable(date),lease_until:nullable(date),last_error:nullable(str)})),
 "POST /api/v1/admin/jobs/{id}/retry":obj({id:uuid,status:str}),
 "GET /api/v1/admin/executions":page(obj({id:uuid,state:str,checked_at:date,execution_id:str,workflow_id:str,action:str,duration_ms:str})),
 "GET /api/v1/admin/sources":obj({items:array(obj({source:str,count:nullable(int),active:nullable(int),lastImportedAt:nullable(date),configuration:str}))}),
 "GET /api/v1/admin/infrastructure":obj({observedAt:date,version:str,services:array(obj({name:str,state:str,latencyMs:num,message:str}))}),
 "GET /api/v1/admin/audit":page(obj({id:str,actor_id:nullable(uuid),event:str,resource_id:nullable(uuid),created_at:date})),
 "GET /api/v1/admin/access":obj({items:array(obj({user_id:uuid,email:str,role:str,active:bool,mfa_enrolled:bool,created_at:date}))}),
 "POST /api/v1/admin/access/invite":obj({invitation:str,expiresAt:date}),"POST /api/v1/admin/access/{id}":ok,
 "GET /api/v1/admin/quality":obj({items:array(obj({domain:str,status:str,detail:str,evidence:nullable(str)}))}),
 "GET /api/v1/admin/backups":obj({state:str,message:str,lastVerifiedAt:nullable(date)}),
 "GET /api/v1/auth/psc/config":obj({enabled:bool,environment:nullable(str)}),
 "POST /api/v1/auth/psc/start":obj({url:str}),
 "GET /api/v1/auth/psc/callback":obj({redirect:str}),

 "GET /api/v1/me/notifications-settings":obj({configured:bool,link:nullable(obj({discord_user_id:str,connected_at:date})),destinations:array(obj({id:uuid,user_id:nullable(uuid),organization_id:nullable(uuid),enabled:bool,events:array(str),channel_name:nullable(str),target_id:str})),preferences:array(obj({kind:str,discord:bool})),catalog:{type:"object",additionalProperties:str},organizationKinds:array(str)},["configured","link","destinations","preferences","catalog","organizationKinds"]),
 "POST /api/v1/me/notifications-settings/discord/challenge":ok,
 "POST /api/v1/me/notifications-settings/discord/verify":ok,
 "DELETE /api/v1/me/notifications-settings/discord":ok,
 "PUT /api/v1/me/notifications-settings/discord":ok,
 "PUT /api/v1/me/notifications-settings/organizations/{id}/discord":ok,
 "PUT /api/v1/me/notifications-settings/preferences/{kind}":ok,
 "GET /api/v1/me/notifications-settings/deliveries":array(obj({id:uuid,kind:str,status:str,last_error:nullable(str),created_at:date,sent_at:nullable(date)},["id","kind","status","created_at"])),
 "POST /api/v1/internal/automation/cancellation/{id}":obj({status:str,notifications:int},["status"]),
 "GET /api/v1/facilities/{id}":{allOf:[ref("Facility"),obj({missions:array(ref("Mission"))})]},
 "GET /api/v1/health":obj({status:str,application:str},["status","application"]),
 "GET /api/v1/auth/google/config":obj({enabled:bool,clientId:nullable(str)},["enabled","clientId"]),
 "POST /api/v1/auth/google/challenge":obj({nonce:str},["nonce"]),
 "GET /api/v1/auth/csrf":obj({csrfToken:str},["csrfToken"]),
 "POST /api/v1/auth/login":auth,"POST /api/v1/auth/register":auth,"POST /api/v1/auth/google/register":auth,
 "POST /api/v1/auth/google":{oneOf:[auth,obj({registrationRequired:{type:"boolean",enum:[true]}},["registrationRequired"])]},
 "GET /api/v1/auth/google/registration":obj({email:{...str,format:"email"},firstName:str,lastName:str},["email"]),
 "GET /api/v1/auth/me":obj({id:uuid,email:{...str,format:"email"},family:str,terms_version:str,terms_at:date,organizations:array(organization),session},["id","email","family","organizations","session"]),
 "POST /api/v1/auth/logout":ok,
 "GET /api/v1/profile":profile,"PUT /api/v1/profile":ok,
 "PATCH /api/v1/profile/availability":obj({available:array(interval),unavailable:array(interval)},["available","unavailable"]),
 "PUT /api/v1/profile/rpps":obj({status:str,reason:str},["status"]),"POST /api/v1/profile/rpps/retry":obj({status:str,reason:str},["status"]),
 "GET /api/v1/missions/{id}":{allOf:[ref("Mission"),obj({assignments:array(ref("Assignment")),application_count:int,can_manage:bool,events:array(obj({event:str,created_at:date}))})]},
 "GET /api/v1/applications/{id}":ref("Application"),
 "GET /api/v1/me/recommendations":obj({mode:str,generatedAt:date,internal:obj({status:str,rppsStatus:nullable(str),items:array(obj({id:str,title:str,qualification:str,matching_score:nullable(num),match_explanation_id:nullable(str),publicationDate:nullable(date)}))}),external:obj({status:str,personalization:str,items:array(obj({id:str,title:str,source:str,url:str,publicationDate:nullable(date),importedAt:nullable(date),sourceUpdatedAt:nullable(date)})),sources:array(obj({provider:str,status:str,created_at:date}))})}),
 "GET /api/v1/me/matches":{...page(match),properties:{...page(match).properties,rppsStatus:str}},
 "GET /api/v1/missions/{id}/candidates":page(match),
 "GET /api/v1/matches/{id}/explanation":obj({_id:str,ownerId:uuid,missionId:uuid,profileVersion:str,missionVersion:int,missionStatus:str,rulesVersion:str,result:match,stale:bool,notice:nullable(str),createdAt:date,updatedAt:date,expiresAt:date},["missionId","result","stale"]),
 "GET /api/v1/me/listings/{id}/correspondence":obj({id:str,profileCorrespondence:ref("ExternalCorrespondence")}),
 "POST /api/v1/me/favorites":ok,"DELETE /api/v1/me/favorites/{kind}/{id}":ok,
 "POST /api/v1/me/notifications/{id}/read":ok,
 "GET /api/v1/dashboards":obj({family:{...str,enum:["NURSE","ENTERPRISE"]},profile:obj({display_name:str,rpps_status:str,available:array(interval)}),counts:{type:"object",additionalProperties:{oneOf:[int,{type:"string",pattern:"^[0-9]+$"}]}},organizations:array(organization)},["family","counts"]),
 "GET /api/v1/me/organizations":obj({organizations:array(organization),links:array(obj({agency_id:uuid,establishment_id:uuid}))},["organizations","links"]),
 "PUT /api/v1/organizations/{id}":ok,
 "GET /api/v1/assignments/{id}/confirmation":obj({status:str,document_id:nullable(uuid),mission_version:int,template_version:int},["status","document_id"]),
 "GET /api/v1/me/bank-details":obj({iban:nullable(str),fictional:bool,required:bool,document:nullable(obj({id:uuid,mime:str,size_bytes:int,created_at:date}))},["iban","required","document"]),
 "GET /api/v1/reference-data":obj({qualifications:array(str),ideServices:array(str),populations:array(str),blocks:array(str),blockSpecialties:array(str),shifts:array(str),salary:obj({currency:str,unit:str,gross:bool}),timezone:str,intervalConvention:str,search:obj({sameDimension:str,withinBranch:str,branches:str,dateWindow:str}),matching:{type:"object",additionalProperties:true},limits:obj({pageSize:int,maxPageSize:int,maxRadiusKm:int,documentMiB:int}),termsVersion:str}),
 "GET /api/v1/reference-data/finess":{...page(finess),properties:{...page(finess).properties,generated_at:date,imported_at:date,source_url:str,sha256:str,grantsOrganizationAccess:{type:"boolean",enum:[false]}}},
 "GET /api/v1/reference-data/finess/{finess}":obj({establishment:nullable(finess),status:{...str,enum:["FOUND_IN_SNAPSHOT","NOT_IN_SNAPSHOT"]},generated_at:date,imported_at:date,source_url:str,sha256:str,grantsOrganizationAccess:{type:"boolean",enum:[false]}},["establishment","status","grantsOrganizationAccess"]),
 "POST /api/v1/internal/automation/matches/{id}":obj({status:str,notifications:int},["status"]),
 "POST /api/v1/internal/automation/jobs/dispatch":obj({processed:int},["processed"]),
 "POST /api/v1/internal/automation/jobs/refresh-offers":obj({providers:array(obj({provider:str,status:str,accepted:int},["provider","status","accepted"]))},["providers"]),
 "POST /api/v1/internal/automation/jobs/maintenance":ok,
 "POST /api/v1/internal/automation/reminders":obj({status:str,notifications:int},["status","notifications"]),
 "POST /api/v1/internal/automation/confirmation/{id}":obj({status:str,documentId:uuid,done:bool},["status"]),
 "GET /api/v1/me/closure-request":obj({request:nullable(closure)},["request"]),
 "POST /api/v1/me/closure-request":closure,"DELETE /api/v1/me/closure-request":closure,
};
