import {AdminClientRequestsController} from './client-requests';
import {discordApi,discordConfigured} from '../notifications/discord-client';
import {AdminOperationsController} from './operations';
import {RefreshModule} from '../public-data/refresh.service';
import {Body,Controller,Get,Post,Req,Param,Query,Module,UseGuards,ParseUUIDPipe,BadRequestException,ConflictException,NotFoundException} from '@nestjs/common';
import {Request} from 'express';
import {IsBoolean,IsEmail,IsIn,IsOptional,IsString,Length} from 'class-validator';
import {randomBytes} from 'node:crypto';
import {Database,audit,SqlClient} from '../database/database';
import {PageDto} from '../common/page.dto';
import {MatchingService,MatchingModule} from '../matching/matching.module';
import {AdminAuthController,AdminGuard,authorizeAdmin,hashInvitation} from './admin-auth';
import {AdminRole} from './permissions';
class Search extends PageDto {@IsOptional() @IsString() @Length(0,100) q?:string;@IsOptional() @IsString() @Length(0,50) status?:string;@IsOptional() @IsString() @Length(0,100) event?:string;}
class Reason {@IsString() @Length(8,500) reason!:string;}
class State extends Reason {@IsBoolean() active!:boolean;}
class Access extends State {@IsIn(['OWNER','SUPPORT','OPS','AUDITOR']) role!:AdminRole;}
class Invite extends Reason {@IsEmail() @Length(3,254) email!:string;@IsIn(['OWNER','SUPPORT','OPS','AUDITOR']) role!:AdminRole;}
const scalar=(rows:any[])=>Number(rows[0]?.count??0);
async function lockAccess(em:SqlClient){await em.query("SELECT pg_advisory_xact_lock(1789381700)");}
async function protectOwner(em:SqlClient,id:string,losesOwner:boolean){if(!losesOwner)return;const [p]=await em.query("SELECT role,active FROM platform_admin WHERE user_id=$1",[id]);if(p?.role==='OWNER'&&p.active&&scalar(await em.query("SELECT count(*) FROM platform_admin p JOIN account a ON a.id=p.user_id WHERE p.role='OWNER' AND p.active AND a.active AND a.password_hash<>'ADMIN_ACTIVATION_PENDING' AND p.invitation_hash IS NULL"))<=1)throw new ConflictException('Le dernier responsable doit conserver son accès.');}
@Controller('admin') @UseGuards(AdminGuard)
export class AdminController {
 constructor(private readonly db:Database,private readonly matching:MatchingService){}
 private async page(sql:string,params:unknown[],p:PageDto){const total=scalar(await this.db.query(`SELECT count(*) FROM (${sql}) result`,params));const items=await this.db.query(sql+` LIMIT $${params.length+1} OFFSET $${params.length+2}`,[...params,p.limit,p.offset]);return {items,total,limit:p.limit,offset:p.offset};}
 @Get('overview') async overview(@Req() r:Request){authorizeAdmin(r,'overview');const [row]=await this.db.query(`SELECT (SELECT count(*)::int FROM account WHERE active) accounts,(SELECT count(*)::int FROM organization) organizations,(SELECT count(*)::int FROM application WHERE status IN('SUBMITTED','SELECTED')) applications,(SELECT count(*)::int FROM outbox WHERE completed_at IS NULL) "pendingEvents",(SELECT count(*)::int FROM outbox WHERE completed_at IS NULL AND attempts>0 AND last_error IS NOT NULL) "failedEvents",(SELECT count(*)::int FROM document WHERE status='READY') documents`);const states=await this.db.query('SELECT status,count(*)::int AS count FROM mission GROUP BY status');return {observedAt:new Date().toISOString(),counts:{...row,missions:Object.fromEntries(['DRAFT','OPEN','FILLED','COMPLETED','CANCELLED'].map(s=>[s,states.find(x=>x.status===s)?.count??0]))},alerts:[...(row.failedEvents?[{kind:'automation',message:`${row.failedEvents} événements nécessitent une vérification.`,href:'/jobs?status=failed'}]:[]),{kind:'backup',message:'Consultez la dernière preuve de restauration et ses limites.',href:'/backups'}]};}
 @Get('accounts') accounts(@Req() r:Request,@Query() p:Search){authorizeAdmin(r,'accounts');return this.page(`SELECT a.id,a.email,a.family,a.active,a.created_at,p.rpps_status,p.rpps_checked_at,COALESCE((SELECT jsonb_agg(jsonb_build_object('id',o.id,'name',o.name,'kind',o.kind)) FROM membership m JOIN organization o ON o.id=m.organization_id WHERE m.user_id=a.id AND m.active),'[]') organizations FROM account a LEFT JOIN profile p ON p.user_id=a.id WHERE ($1='' OR a.email ILIKE '%'||$1||'%') ORDER BY a.created_at DESC,a.id`,[p.q??''],p);}
 @Get('accounts/:id') async account(@Req() r:Request,@Param('id',ParseUUIDPipe) id:string){const actor=authorizeAdmin(r,'accounts');const [account]=await this.db.query('SELECT id,email,family,active,created_at FROM account WHERE id=$1',[id]);if(!account)throw new NotFoundException();const [profile]=await this.db.query('SELECT display_name,qualifications,rpps_status,rpps_checked_at,updated_at FROM profile WHERE user_id=$1',[id]);await audit(this.db,actor,'ADMIN_ACCOUNT_VIEWED',id);return {account,profile:profile??null,organizations:await this.db.query('SELECT o.id,o.name,o.kind,m.active FROM organization o JOIN membership m ON m.organization_id=o.id WHERE m.user_id=$1',[id]),documents:await this.db.query('SELECT id,kind,mime,status,size_bytes,created_at FROM document WHERE owner_id=$1 ORDER BY created_at DESC LIMIT 50',[id]),audit:await this.db.query('SELECT event,created_at FROM audit WHERE resource_id=$1 ORDER BY created_at DESC LIMIT 50',[id])};}
 @Post('accounts/:id/state') async state(@Req() r:Request,@Param('id',ParseUUIDPipe) id:string,@Body() b:State){const actor=authorizeAdmin(r,'accounts:write',true);return this.db.transaction(async em=>{await lockAccess(em);const [privileged]=await em.query('SELECT 1 FROM platform_admin WHERE user_id=$1',[id]);if(privileged)authorizeAdmin(r,'access:write',true);await protectOwner(em,id,!b.active);const rows=await em.query('UPDATE account SET active=$2,session_version=session_version+1 WHERE id=$1 RETURNING id',[id,b.active]);if(!rows.length)throw new NotFoundException();await em.query("DELETE FROM session WHERE sess->>'userId'=$1",[id]);await em.query("DELETE FROM admin_session WHERE sess->>'adminId'=$1",[id]);await audit(em,actor,b.active?'ADMIN_ACCOUNT_REACTIVATED':'ADMIN_ACCOUNT_SUSPENDED',id,{reason:b.reason});return {ok:true};});}
 @Post('accounts/:id/revoke') async revoke(@Req() r:Request,@Param('id',ParseUUIDPipe) id:string,@Body() b:Reason){const actor=authorizeAdmin(r,'accounts:write',true);return this.db.transaction(async em=>{await lockAccess(em);if((await em.query('SELECT 1 FROM platform_admin WHERE user_id=$1',[id])).length)authorizeAdmin(r,'access:write',true);if(!(await em.query('UPDATE account SET session_version=session_version+1 WHERE id=$1 RETURNING id',[id])).length)throw new NotFoundException();await em.query("DELETE FROM session WHERE sess->>'userId'=$1",[id]);await em.query("DELETE FROM admin_session WHERE sess->>'adminId'=$1",[id]);await audit(em,actor,'ADMIN_SESSIONS_REVOKED',id,{reason:b.reason});return {ok:true};});}
 @Get('organizations') organizations(@Req() r:Request,@Query() p:Search){authorizeAdmin(r,'organizations');return this.page("SELECT o.id,o.name,o.kind,o.address,o.finess,o.siret,(SELECT count(*)::int FROM membership m WHERE m.organization_id=o.id AND m.active) AS members FROM organization o WHERE ($1='' OR o.name ILIKE '%'||$1||'%') ORDER BY o.name,o.id",[p.q??''],p);}
 @Get('missions') missions(@Req() r:Request,@Query() p:Search){authorizeAdmin(r,'missions');return this.page("SELECT m.id,m.title,m.status,m.start_at,m.end_at,m.qualification,a.name agency_name,e.name establishment_name,(SELECT count(*)::int FROM application c WHERE c.mission_id=m.id) application_count FROM mission m LEFT JOIN organization a ON a.id=m.agency_id JOIN organization e ON e.id=m.establishment_id WHERE ($1='' OR m.title ILIKE '%'||$1||'%') AND ($2='' OR m.status=$2) ORDER BY m.created_at DESC,m.id",[p.q??'',p.status??''],p);}
 @Get('missions/:id') async mission(@Req() r:Request,@Param('id',ParseUUIDPipe) id:string){authorizeAdmin(r,'missions');const [mission]=await this.db.query('SELECT id,title,status,version,qualification,service,population,block,specialty,required_skills,desired_skills,start_at,end_at,shift,address,hourly_salary,agency_id,establishment_id FROM mission WHERE id=$1',[id]);if(!mission)throw new NotFoundException();return {mission,applications:await this.db.query('SELECT id,status,consent_version,updated_at FROM application WHERE mission_id=$1 ORDER BY updated_at DESC LIMIT 50',[id]),assignments:await this.db.query('SELECT id,status,start_at,end_at,created_at FROM assignment WHERE mission_id=$1 ORDER BY created_at DESC LIMIT 50',[id]),events:await this.db.query("SELECT event,created_at,actor_id FROM audit WHERE resource_id=$1 OR details->>'missionId'=$1 ORDER BY created_at DESC LIMIT 100",[id])};}
 @Get('jobs') jobs(@Req() r:Request,@Query() p:Search){authorizeAdmin(r,'jobs');return this.page(`SELECT id,event,attempts,created_at,available_at,completed_at,lease_until,CASE WHEN last_error IS NULL THEN NULL ELSE 'Échec du traitement ; consulter la procédure de reprise.' END last_error FROM outbox WHERE ($1='' OR ($1='failed' AND completed_at IS NULL AND last_error IS NOT NULL) OR ($1='pending' AND completed_at IS NULL) OR ($1='completed' AND completed_at IS NOT NULL)) ORDER BY created_at DESC,id`,[p.status??''],p);}
 @Post('jobs/:id/retry') async retry(@Req() r:Request,@Param('id',ParseUUIDPipe) id:string,@Body() b:Reason){const actor=authorizeAdmin(r,'jobs:retry',true);return this.db.transaction(async em=>{const [job]=await em.query('SELECT * FROM outbox WHERE id=$1 FOR UPDATE',[id]);if(!job||!['MissionOPEN','MatchRequested','AssignmentCreated','MissionCANCELLED'].includes(job.event))throw new NotFoundException();if(job.completed_at)return {id,status:'ALREADY_COMPLETED'};if(new Date(job.lease_until??0).getTime()>Date.now())throw new ConflictException('Traitement en cours.');await em.query('UPDATE outbox SET attempts=0,available_at=now(),lease_until=NULL,lease_token=NULL,last_error=NULL WHERE id=$1',[id]);await audit(em,actor,'ADMIN_OUTBOX_REQUEUED',id,{reason:b.reason,previousAttempts:job.attempts});return {id,status:'QUEUED'};});}
 @Get('executions') executions(@Req() r:Request,@Query() p:Search){authorizeAdmin(r,'jobs');return this.page("SELECT id,state,checked_at,summary->>'executionId' execution_id,summary->>'workflowId' workflow_id,summary->>'action' action,summary->>'durationMs' duration_ms FROM operational_check WHERE service='n8n-execution' ORDER BY checked_at DESC,id",[],p);}
 @Get('sources') async sources(@Req() r:Request){authorizeAdmin(r,'sources');const stats=await this.db.query('SELECT source,count(*)::int count,count(*) FILTER(WHERE active)::int active,max(imported_at) "lastImportedAt" FROM external_offer GROUP BY source');const runs=await this.db.query('SELECT DISTINCT ON(provider) provider,status,created_at FROM import_run ORDER BY provider,created_at DESC');return {items:[...stats.map(s=>({...s,configuration:'configured',lastRun:runs.find(x=>x.provider===s.source)??null})),...['Google','Annuaire Santé','Pro Santé Connect','FINESS'].map(source=>({source,configuration:source==='Google'?(process.env.GOOGLE_CLIENT_ID?'configured':'missing'):source==='Annuaire Santé'?(process.env.RPPS_API_KEY?'configured':'missing'):source==='Pro Santé Connect'?(process.env.PSC_ENABLED==='true'?'configured':'missing'):'unknown',count:null,active:null,lastImportedAt:null}))]};}
 @Get('infrastructure') async infrastructure(@Req() r:Request){authorizeAdmin(r,'infrastructure');const services:any[]=[];for(const [name,check] of [['PostgreSQL/PostGIS',async()=>{await this.db.query('SELECT PostGIS_Version()');}],['MongoDB',async()=>{await this.matching.connection.asPromise();await this.matching.connection.db!.admin().ping();}]] as const){const start=Date.now();try{await check();services.push({name,state:'ready',latencyMs:Date.now()-start,message:'Connexion vérifiée lors de cette requête.'});}catch{services.push({name,state:'unavailable',message:'Échec du contrôle de disponibilité.'});}}
 let discordState='missing',discordMessage='Connexion Discord non configuree.';
 if(discordConfigured()){try{const bot=await discordApi('/users/@me');if(!bot?.id||bot.bot!==true)throw Error('Invalid bot');discordState='ready';discordMessage='Authentification du bot verifiee. La reception des messages prives depend du serveur partage et des autorisations du destinataire.';}catch{discordState='unavailable';discordMessage='Le controle de connexion du bot a echoue. Verifiez le relais n8n et son identifiant Discord.';}}
 const [heartbeat]=await this.db.query("SELECT checked_at FROM operational_check WHERE service='cloud-dispatch' ORDER BY checked_at DESC LIMIT 1");
 return {observedAt:new Date().toISOString(),version:process.env.VERCEL_GIT_COMMIT_SHA??'local',services:[...services,{name:'Documents',state:process.env.DOCUMENT_STORAGE==='postgres'?'configured':'local',message:process.env.DOCUMENT_STORAGE==='postgres'?'Stockage chiffré PostgreSQL ; ouverture à vérifier par recette.':'Stockage local.'},{name:'Vault',state:'local',message:'Coffre conservé sur le PC ; secrets serveur copiés dans Vercel conformément au choix du propriétaire.'},{name:'n8n / Discord',state:discordState,message:discordMessage},{name:'Traitement cloud',state:heartbeat&&Date.now()-new Date(heartbeat.checked_at).getTime()<70*60000?'ready':'unknown',message:heartbeat?'Dernier traitement : '+new Date(heartbeat.checked_at).toISOString():'Aucun traitement cloud observe.'}]};}
 @Get('audit') logs(@Req() r:Request,@Query() p:Search){authorizeAdmin(r,'audit');return this.page("SELECT id,actor_id,event,resource_id,created_at FROM audit WHERE ($1='' OR event=$1) ORDER BY created_at DESC,id DESC",[p.event??''],p);}
 @Get('access') async access(@Req() r:Request){authorizeAdmin(r,'access');return {items:await this.db.query("SELECT p.user_id,a.email,p.role,p.active,(a.password_hash<>'ADMIN_ACTIVATION_PENDING' AND p.invitation_hash IS NULL) activation_completed,p.created_at FROM platform_admin p JOIN account a ON a.id=p.user_id ORDER BY p.created_at")};}
 @Post('access/invite') async invite(@Req() r:Request,@Body() b:Invite){const actor=authorizeAdmin(r,'access:write',true),invitation=randomBytes(32).toString('base64url');await this.db.transaction(async em=>{await lockAccess(em);const [a]=await em.query('SELECT id FROM account WHERE lower(email)=lower($1) AND active',[b.email]);if(!a)throw new NotFoundException('Compte existant actif nécessaire.');if((await em.query('SELECT 1 FROM platform_admin WHERE user_id=$1',[a.id])).length)throw new ConflictException('Cet accès existe déjà.');await em.query("INSERT INTO platform_admin(user_id,role,invitation_hash,invitation_expires_at) VALUES($1,$2,$3,now()+interval '24 hours')",[a.id,b.role,hashInvitation(invitation)]);await audit(em,actor,'ADMIN_INVITED',a.id,{role:b.role,reason:b.reason});});return {invitation,expiresAt:new Date(Date.now()+86400000).toISOString()};}
 @Post('access/:id') async updateAccess(@Req() r:Request,@Param('id',ParseUUIDPipe) id:string,@Body() b:Access){const actor=authorizeAdmin(r,'access:write',true);return this.db.transaction(async em=>{await lockAccess(em);await protectOwner(em,id,!b.active||b.role!=='OWNER');if(!(await em.query('UPDATE platform_admin SET role=$2,active=$3,version=version+1 WHERE user_id=$1 RETURNING user_id',[id,b.role,b.active])).length)throw new NotFoundException();await em.query("DELETE FROM admin_session WHERE sess->>'adminId'=$1",[id]);await audit(em,actor,'ADMIN_ACCESS_CHANGED',id,{role:b.role,active:b.active,reason:b.reason});return {ok:true};});}
 @Get('quality') quality(@Req() r:Request){authorizeAdmin(r,'quality');return {items:[{domain:'RGAA',status:'non audité',detail:'Contrôles ciblés à distinguer d’un audit RGAA complet.',evidence:'/accessibilite'},{domain:'RGESN',status:'démarche en cours',detail:'Aucun score ni certification déclaré.',evidence:'/ecoconception'},{domain:'Recommandations',status:'mixte validé',detail:'Missions internes compatibles et offres externes : pertinence puis date de publication connue, dans deux groupes distincts.',evidence:null}]};}
 @Get('backups') async backups(@Req() r:Request){authorizeAdmin(r,'backups');const [proof]=await this.db.query("SELECT state,checked_at,summary FROM operational_check WHERE service='backup-restore' ORDER BY checked_at DESC LIMIT 1");return {state:proof?.state??'unknown',message:proof?'Restauration isolee verifiee. Aucune restauration en production ni sauvegarde quotidienne automatique.':'Aucune preuve de restauration enregistree.',lastVerifiedAt:proof?.checked_at??null,proof:proof?.summary??null};}

}
@Module({imports:[MatchingModule,RefreshModule],controllers:[AdminClientRequestsController,AdminAuthController,AdminController,AdminOperationsController],providers:[AdminGuard]})
export class AdminModule {}
