import { useState } from 'react';
import { Link, useLocation, useSearchParams } from 'react-router';
import { Button } from '../ui/Button';
import { Badge, DataState, Table, date, fmt, useData, type Action, type User, type Row } from './App';

type Props = { user: User; action: (action: Action) => void; version: number };
const readable: Record<string, string> = {
  SUCCESS: 'Terminé', FAILED: 'Échec', RUNNING: 'En cours',
  TO_REVIEW: 'À examiner', REVIEWED: 'Examen consigné', NEEDS_INFORMATION: 'Informations nécessaires',
  INVESTIGATING: 'En cours d’analyse', RESOLVED: 'Résolu', OPEN: 'Ouvert', FRANCE_TRAVAIL: 'France Travail', JOBSPIPE: 'JobsPipe',
  QUALIFICATION_MISSING: 'Qualification requise absente', REQUIRED_SKILLS_MISSING: 'Compétences obligatoires manquantes', EXPERIENCE_INSUFFICIENT: 'Expérience insuffisante',
  NOT_FULLY_AVAILABLE: 'Disponibilité incomplète', ASSIGNMENT_CONFLICT: 'Chevauchement avec une affectation', SHIFT_NOT_ACCEPTED: 'Horaire non accepté', MOBILITY_INCOMPLETE: 'Mobilité non renseignée', OUTSIDE_RADIUS: 'Hors du rayon de mobilité', MISSION_NOT_OPEN: 'Mission non ouverte',
};
const text = (v: unknown) => readable[String(v)] || (String(v).startsWith('RPPS_') ? `Vérification RPPS : ${fmt(String(v).slice(5))}` : fmt(v));
const permission = (user: User, name: string) => user.permissions.includes(name);
function ReadOnly({ allowed }: { allowed: boolean }) { return allowed ? null : <p className="admin-caption">Votre rôle permet la consultation uniquement.</p>; }
function Pager({ total, count }: { total: number; count: number }) {
  const [params, setParams] = useSearchParams(); const offset = Math.max(0, Number(params.get('offset')) || 0);
  function go(next: number) { const p = new URLSearchParams(params); p.set('offset', String(next)); setParams(p); }
  return <div className="admin-pagination"><p>{total} résultats · {count ? offset + 1 : 0}–{count ? offset + count : 0}</p><Button variant="outline" disabled={!offset} onClick={() => go(Math.max(0, offset - 20))}>Précédent</Button><Button variant="outline" disabled={offset + 20 >= total} onClick={() => go(offset + 20)}>Suivant</Button></div>;
}
export function OrganizationDetail({ id, user, action, version }: Props & { id: string }) {
  const [copyStatus, setCopyStatus] = useState('');
  const request = useData(`/organizations/${encodeURIComponent(id)}`, version); const location = useLocation(); const can = permission(user, 'organizations:write');
  return <><Link to={location.state?.from || '/organizations'}>← Retour aux organisations</Link><DataState request={request}>{d => <>
    <section className="admin-panel"><h2>{d.organization.name}</h2><div className="admin-organization-reference"><label>Référence de l’organisation<input readOnly value={d.organization.id} onFocus={e => e.currentTarget.select()} /></label><Button variant="outline" onClick={async () => { try { await navigator.clipboard.writeText(d.organization.id); setCopyStatus('Référence copiée.'); } catch { setCopyStatus('Copie indisponible. Sélectionnez la référence et copiez-la manuellement.'); } }}>Copier la référence</Button><p role="status">{copyStatus}</p></div><dl className="admin-facts">{[['Type', d.organization.kind], ['Adresse', d.organization.address], ['FINESS', d.organization.finess], ['SIRET', d.organization.siret]].map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{fmt(value)}</dd></div>)}</dl></section>
    <section className="admin-panel"><h2>Membres de l’organisation</h2><p>Un rattachement actif donne au compte entreprise accès aux données et actions métier de cette organisation.</p><ReadOnly allowed={can} /><Button disabled={!can} onClick={() => action({ title: 'Rattacher un compte entreprise', path: `/organizations/${id}/members`, body: { active: true }, inputs: [{ name: 'email', label: 'Adresse e-mail du compte entreprise existant', type: 'email' }], consequence: 'Ce compte existant pourra consulter et gérer les données de cette organisation selon les règles métier. Aucun nouveau compte ni rôle d’organisation n’est créé.' })}>Rattacher un membre</Button><Table rows={d.members || []} cols={[['email', 'Compte'], ['active', 'Rattachement actif'], ['account_active', 'Compte actif']]} extra={r => <Button size="sm" variant="outline" disabled={!can} onClick={() => action({ title: r.active ? 'Retirer ce rattachement' : 'Réactiver ce rattachement', path: `/organizations/${id}/members`, body: { email: r.email, active: !r.active }, consequence: 'Les autorisations métier liées à ce rattachement seront mises à jour. Les autres organisations du compte restent inchangées.' })}>{r.active ? 'Retirer' : 'Réactiver'}</Button>} /></section>
    <section className="admin-panel"><h2>Liens entre agence et établissement</h2><p>Une agence liée peut intervenir dans le parcours métier de l’établissement. Le retrait est bloqué si des missions actives dépendent du lien.</p><Button disabled={!can} onClick={() => action({ title: 'Relier une organisation', path: `/organizations/${id}/links`, body: { active: true }, inputs: [{ name: 'otherOrganizationId', label: 'Identifiant de l’organisation de type opposé', type: 'text' }], consequence: 'Ce lien autorise la collaboration métier entre l’agence et l’établissement identifiés. Vérifiez leur accord et les références avant confirmation.' })}>Créer un lien</Button><Table rows={d.links || []} cols={[['agency_name', 'Agence'], ['establishment_name', 'Établissement']]} extra={r => <Button size="sm" variant="outline" disabled={!can} onClick={() => action({ title: 'Retirer le lien', path: `/organizations/${id}/links`, body: { otherOrganizationId: r.agency_id === id ? r.establishment_id : r.agency_id, active: false }, consequence: 'La collaboration par ce lien sera retirée. Le serveur refusera si des missions actives en dépendent.' })}>Retirer le lien</Button>} /></section>
  </>}</DataState></>;
}
export function Verification({ id, user, action, version }: Props & { id: string }) {
  const req = useData(`/accounts/${encodeURIComponent(id)}/verification`, version); const can = permission(user, 'verification:write');
  return <section className="admin-panel"><h2>Annuaire, identité et examen manuel</h2><p>Trois preuves distinctes : une correspondance dans l’annuaire, une authentification professionnelle et un examen du dossier. Consigner un examen ne valide ni le RPPS ni l’éligibilité professionnelle.</p><DataState request={req}>{d => <><dl className="admin-facts"><div><dt>Annuaire professionnel</dt><dd><Badge value={d.directory?.status} /></dd></div><div><dt>Dernier contrôle annuaire</dt><dd>{date(d.directory?.checkedAt)}</dd></div><div><dt>Motif annuaire</dt><dd>{text(d.directory?.reason)}</dd></div><div><dt>Identité à examiner</dt><dd>{fmt(d.directory?.identityReview)}</dd></div><div><dt>Authentification professionnelle</dt><dd>{d.professionalIdentity ? date(d.professionalIdentity.authenticatedAt) : 'Aucune preuve enregistrée'}</dd></div><div><dt>Émetteur de l’identité</dt><dd>{d.professionalIdentity?.issuer || 'Non renseigné'}</dd></div></dl><ReadOnly allowed={can} /><div className="admin-actions">{['TO_REVIEW', 'REVIEWED', 'NEEDS_INFORMATION'].map(state => <Button key={state} disabled={!can} variant="outline" onClick={() => action({ title: text(state), path: `/accounts/${id}/verification`, body: { state }, consequence: 'Cette action consigne uniquement un examen manuel motivé. Elle ne modifie pas le résultat RPPS et ne donne aucun droit professionnel supplémentaire.' })}>{text(state)}</Button>)}</div><Table rows={(d.reviews || []).map((r: Row) => ({ ...r, state: text(r.state) }))} cols={[['state', 'Examen'], ['reason', 'Justification'], ['actor_id', 'Auteur'], ['created_at', 'Date']]} /></>}</DataState></section>;
}
export function Matching({ id }: { id: string }) {
  const [params] = useSearchParams(); const offset = Math.max(0, Number(params.get('offset')) || 0); const request = useData(`/missions/${encodeURIComponent(id)}/matching?limit=20&offset=${offset}`);
  return <><Link to={`/missions/${id}`}>← Retour à la mission</Link><section className="admin-panel"><h2>Explications de matching enregistrées</h2><p>Lecture des calculs conservés. Aucun recalcul, classement actuel ou décision d’affectation n’est effectué depuis cet écran.</p></section><DataState request={request}>{d => <>{!(d.items || []).length && <div className="admin-empty"><h2>Aucune explication conservée</h2><p>Il peut ne pas y avoir de calcul enregistré ou sa durée de conservation est dépassée.</p></div>}{(d.items || []).map((r: Row) => { const result = r.result || {}; const expired = r.expiresAt && Date.parse(r.expiresAt) <= Date.now(); const reasons = result.reasons || []; return <article key={r.id} className="admin-panel admin-match"><header><h2>Profil {r.ownerId}</h2><Badge value={result.eligible === true ? 'Éligible lors du calcul' : result.eligible === false ? 'Non éligible lors du calcul' : 'Résultat inconnu'} /></header>{r.stale && <div className="admin-message">Version dépassée : le profil, la mission ou les règles ont changé.</div>}{expired && <div className="admin-message">Explication expirée : sa validité temporelle est dépassée.</div>}<dl className="admin-facts"><div><dt>Score enregistré</dt><dd>{result.score == null ? 'Non calculé' : `${result.score} / 100`}</dd></div><div><dt>Distance</dt><dd>{result.distanceKm == null ? 'Non connue' : `${Number(result.distanceKm).toLocaleString('fr-FR', { maximumFractionDigits: 1 })} km`}</dd></div><div><dt>Calcul</dt><dd>{date(r.createdAt)}</dd></div><div><dt>Expiration</dt><dd>{date(r.expiresAt)}</dd></div></dl>{reasons.length > 0 && <><h3>Motifs d’exclusion</h3><ul className="admin-reasons">{reasons.map((reason: string, i: number) => <li key={i}>{text(reason)}</li>)}</ul></>}{result.components && <><h3>Composantes du score</h3><dl className="admin-facts">{Object.entries(result.components).map(([k, v]) => <div key={k}><dt>{{ C: 'Compétences souhaitées', Z: 'Proximité', D: 'Préférences horaires', E: 'Expérience' }[k] || k}</dt><dd>{typeof v === 'number' ? `${Math.round(v * 100)} %` : 'Non renseigné'}</dd></div>)}</dl><p className="admin-caption">Composantes normalisées du calcul enregistré ; ce ne sont pas des probabilités de réussite.</p></>}<details><summary>Versions et traçabilité</summary><dl className="admin-facts">{[['Calcul', r.id], ['Mission', r.missionVersion], ['Profil', r.profileVersion], ['Règles', r.rulesVersion]].map(([k, v]) => <div key={k}><dt>{k}</dt><dd>{fmt(v)}</dd></div>)}</dl></details></article>; })}<Pager total={d.total || 0} count={d.items?.length || 0} /></>}</DataState></>;
}
const incidentServices = ['API', 'POSTGRES', 'MONGODB', 'N8N', 'DISCORD', 'IMPORTS', 'DOCUMENTS', 'VAULT'];
function IncidentActions({ row, user, action }: Props & { row: Row }) { return <div className="admin-actions">{['OPEN', 'INVESTIGATING', 'RESOLVED'].filter(s => s !== row.state).map(state => <Button size="sm" variant="outline" disabled={!permission(user, 'incidents:write')} key={state} onClick={() => action({ title: `Incident : ${text(state)}`, path: `/incidents/${row.id}`, body: { state }, consequence: 'Le changement de statut et sa justification seront ajoutés au suivi de cet incident. Il ne modifie pas automatiquement le service.' })}>{text(state)}</Button>)}</div>; }
export function Operations({ user, action, version }: Props) {
  const req = useData('/operations', version); const can = permission(user, 'sources:write');
  return <DataState request={req}>{d => <><p className="admin-caption">Observation : {date(d.observedAt)} · Europe/Paris</p><ReadOnly allowed={can} />{(d.sources || []).map((source: Row) => <section className="admin-panel" key={source.provider}><h2>{text(source.provider)}</h2><Badge value={source.enabled ? 'Imports autorisés' : 'Imports en pause'} /><dl className="admin-facts"><div><dt>Dernier changement</dt><dd>{date(source.updated_at)}</dd></div><div><dt>Prochain déclenchement</dt><dd>{source.nextScheduleLabel || 'Non connu'}</dd></div><div><dt>Dernière exécution</dt><dd>{source.lastRun ? text(source.lastRun.status) : 'Aucune preuve enregistrée'}</dd></div></dl>{source.lastRun && <dl className="admin-facts"><div><dt>Date du dernier import</dt><dd>{date(source.lastRun.created_at)}</dd></div>{[['Offres acceptées', source.lastRun.accepted], ['Offres rejetées', source.lastRun.rejected], ['Doublons', source.lastRun.duplicates]].map(([label,value]) => <div key={String(label)}><dt>{label}</dt><dd>{fmt(value)}</dd></div>)}{source.lastRun.error && <div><dt>Dernier constat</dt><dd>{source.lastRun.error}</dd></div>}</dl>}{source.counts && <dl className="admin-facts">{Object.entries(source.counts).filter(([key]) => key !== 'source').map(([key, value]) => <div key={key}><dt>{{ total: 'Offres référencées', active: 'Offres actives', count: 'Offres référencées' }[key] || key}</dt><dd>{fmt(value)}</dd></div>)}</dl>}<div className="admin-actions"><Button variant="outline" disabled={!can || !['FRANCE_TRAVAIL', 'JOBSPIPE'].includes(source.provider)} onClick={() => action({ title: source.enabled ? 'Mettre les imports en pause' : 'Autoriser les imports', path: `/operations/sources/${source.provider}/state`, body: { enabled: !source.enabled }, consequence: 'Ce réglage concerne uniquement les imports planifiés de cette source. Il ne désactive ni la connexion des utilisateurs ni les autres sources.' })}>{source.enabled ? 'Mettre en pause' : 'Réactiver les imports'}</Button><Button disabled={!can || !['FRANCE_TRAVAIL', 'JOBSPIPE'].includes(source.provider)} onClick={() => action({ title: 'Déclencher un import borné', path: `/operations/sources/${source.provider}/refresh`, consequence: 'Ce déclenchement manuel reste possible même si la planification est en pause. Un lot limité sera traité selon les règles de dédoublonnage existantes. Un import déjà en cours peut empêcher ce déclenchement.' })}>Actualiser cette source</Button></div></section>)}<section className="admin-panel"><h2>Incidents signalés</h2><Table rows={(d.incidents || []).map((r: Row) => ({ ...r, state: text(r.state) }))} cols={[['service', 'Service'], ['state', 'Statut'], ['impact', 'Impact'], ['owner_label', 'Responsable'], ['updated_at', 'Mise à jour']]} />{permission(user, 'infrastructure') && <Link to="/incidents">Consulter le suivi des incidents →</Link>}</section></>}</DataState>;
}
export function IncidentList({ user, action, version }: Props) {
  const [params] = useSearchParams(); const offset = Math.max(0, Number(params.get('offset')) || 0); const req = useData(`/incidents?limit=20&offset=${offset}`, version); const can = permission(user, 'incidents:write');
  return <><p className="admin-caption">Suivi déclaratif des incidents. Un incident résolu ne constitue pas un contrôle automatique de disponibilité.</p><ReadOnly allowed={can} /><Button disabled={!can} onClick={() => action({ title: 'Signaler un incident', path: '/incidents', inputs: [{ name: 'service', label: 'Service concerné', options: incidentServices }, { name: 'impact', label: 'Impact observé', type: 'text', maxLength: 500 }, { name: 'ownerLabel', label: 'Responsable du suivi', type: 'text', maxLength: 100 }], consequence: 'Cet incident et son impact seront visibles des opérateurs habilités. Ne saisissez aucun secret ni donnée personnelle dans ce suivi.' })}>Signaler un incident</Button><DataState request={req}>{d => <><Table rows={d.items || []} cols={[['service', 'Service'], ['state', 'Statut'], ['impact', 'Impact'], ['owner_label', 'Responsable'], ['started_at', 'Début'], ['resolved_at', 'Résolution']]} extra={row => <IncidentActions row={row} user={user} action={action} version={version} />} /><Pager total={d.total || 0} count={d.items?.length || 0} /></>}</DataState></>;
}
export function PrivacyRequests({ version }: { version: number }) { const [params] = useSearchParams(); const offset = Math.max(0, Number(params.get('offset')) || 0); const req = useData(`/privacy-requests?limit=20&offset=${offset}`, version); return <><p className="admin-caption">Suivi en lecture seule des demandes de confidentialité. Aucune approbation ni suppression n’est déclenchée depuis cet écran.</p><DataState request={req}>{d => <><Table rows={d.items || []} cols={[['id', 'Demande'], ['account_id', 'Compte'], ['status', 'État'], ['requested_at', 'Demande reçue'], ['approved_at', 'Approbation'], ['completed_at', 'Fin']]} /><Pager total={d.total || 0} count={d.items?.length || 0} /></>}</DataState></>; }
