import {useSearchParams} from 'react-router';
import {Button} from '../ui/Button';
import {DataState,Table,useData,type Action,type User} from './App';
const labels:Record<string,string>={firstName:'Prénom',lastName:'Nom',email:'E-mail',city:'Ville',phone:'Téléphone',birthDate:'Date de naissance',address:'Adresse postale',postalCode:'Code postal'};
export function PersonalCorrections({user,action,version}:{user:User;action:(a:Action)=>void;version:number}){
 const [params,setParams]=useSearchParams(),offset=Math.max(0,Number(params.get('offset'))||0),req=useData(`/personal-corrections?limit=20&offset=${offset}`,version),can=user.permissions.includes('accounts:write');
 return <><p className="admin-caption">Vérifiez l’identité du demandeur et la correction par un canal fiable. L’approbation applique uniquement le champ affiché. Un changement d’e-mail ferme les sessions existantes ; un changement de nom ou prénom nécessite une nouvelle vérification RPPS.</p><DataState request={req}>{d=><>
 <Table rows={(d.items||[]).map((r:any)=>({...r,fieldLabel:labels[r.field],stateLabel:r.status==='REQUESTED'?'À examiner':r.status==='COMPLETED'?'Corrigée':'Refusée'}))} cols={[["email","Compte"],["fieldLabel","Champ"],["previous_value","Valeur actuelle à la demande"],["proposed_value","Valeur demandée"],["stateLabel","État"],["requested_at","Demande reçue"],["decision_reason","Décision"]]} extra={r=>r.status==='REQUESTED'?<div className="admin-actions"><Button size="sm" disabled={!can} onClick={()=>action({title:'Valider la correction',path:`/personal-corrections/${r.id}/approve`,identityVerification:true,consequence:`${labels[r.field]} : remplacer « ${r.previous_value||'Non renseigné'} » par « ${r.proposed_value||'Non renseigné'} ». Vérifiez cette correction avec le demandeur avant de confirmer.`})}>Valider la correction</Button><Button size="sm" variant="outline" disabled={!can} onClick={()=>action({title:'Refuser la correction',path:`/personal-corrections/${r.id}/reject`,consequence:'Les informations du compte resteront inchangées. Le motif sera visible par le demandeur.'})}>Refuser</Button></div>:null}/>
 <div className="admin-pagination"><p>{d.total} demandes</p><Button variant="outline" disabled={!offset} onClick={()=>setParams({offset:String(Math.max(0,offset-20))})}>Précédent</Button><Button variant="outline" disabled={offset+20>=d.total} onClick={()=>setParams({offset:String(offset+20)})}>Suivant</Button></div>
 </>}</DataState></>;
}
