import { Link, useLocation, useSearchParams } from 'react-router';
import { Button } from '../ui/Button';
import { Badge, DataState, Table, date, useData, type Action, type User, type Row } from './App';

type Props = { user: User; action: (action: Action) => void; version: number };
const stateLabels: Record<string,string> = {REQUESTED:'À examiner',ISSUED:'Lien créé',COMPLETED:'Terminée',REJECTED:'Refusée',APPROVED:'Approuvée',PROCESSING:'Traitement en cours',CANCELLED:'Annulée'};
function RequestPages({ total, count }: { total: number; count: number }) { const [params,setParams]=useSearchParams(); const offset=Math.max(0,Number(params.get('offset'))||0); function move(n:number){const p=new URLSearchParams(params);p.set('offset',String(n));setParams(p);} return <div className="admin-pagination"><p>{total} demandes · {count?offset+1:0}–{count?offset+count:0}</p><Button variant="outline" disabled={!offset} onClick={()=>move(Math.max(0,offset-20))}>Précédent</Button><Button variant="outline" disabled={offset+20>=total} onClick={()=>move(offset+20)}>Suivant</Button></div>; }
export function RecoveryRequests({user,action,version}:Props){
  const [params]=useSearchParams();const accountId=params.get('accountId');const query=new URLSearchParams({limit:'20',offset:String(Math.max(0,Number(params.get('offset'))||0))});if(accountId)query.set('accountId',accountId);const req=useData(`/recovery-requests?${query}`,version);const can=user.permissions.includes('accounts:recover');
  function issue(row:Row){action({title:row.status==='ISSUED'?'Remplacer le lien de récupération':'Créer un lien de récupération',path:`/recovery-requests/${row.id}/issue`,identityVerification:true,consequence:'Connaître une adresse e-mail ne prouve pas l’identité. Vérifiez la personne par un canal de contact existant et fiable avant confirmation. Le lien permet de choisir un nouveau mot de passe, expire après 30 minutes et ne sert qu’une fois. Un nouveau lien invalide le précédent. Aucun e-mail ne sera envoyé automatiquement.'});}
  return <><p className="admin-caption">Récupération d’accès après contrôle manuel d’identité. Aucun lien ni mot de passe n’est conservé dans cette liste.</p>{accountId&&<p className="admin-caption">Demandes du compte {accountId} · <Link to="/recovery-requests">Afficher tous les comptes</Link></p>}{!can&&<p className="admin-caption">Votre rôle permet la consultation uniquement.</p>}<DataState request={req}>{d=><><Table rows={(d.items||[]).map((r:Row)=>({...r,display_status:r.status==='ISSUED'&&Date.parse(r.expires_at)<=Date.now()?'Lien expiré':stateLabels[r.status]||r.status}))} cols={[['email','Compte'],['display_status','État'],['requested_at','Demande'],['issued_at','Émission'],['expires_at','Expiration'],['completed_at','Fin'],['decision_reason','Motif']]} extra={row=><div className="admin-actions">{['REQUESTED','ISSUED'].includes(row.status)&&<><Button size="sm" disabled={!can} onClick={()=>issue(row)}>{row.status==='ISSUED'?'Remplacer le lien':'Créer le lien'}</Button><Button size="sm" variant="outline" disabled={!can} onClick={()=>action({title:'Refuser la demande de récupération',path:`/recovery-requests/${row.id}/reject`,consequence:'Le refus motivé sera enregistré. Aucun nouveau lien de récupération ne sera généré.'})}>Refuser</Button></>}</div>}/><RequestPages total={d.total||0} count={d.items?.length||0}/></>}</DataState></>;
}
export function PrivacyRequestList({version}:Props){const [params]=useSearchParams();const location=useLocation();const query=new URLSearchParams({limit:'20',offset:String(Math.max(0,Number(params.get('offset'))||0))});const accountId=params.get('accountId');if(accountId)query.set('accountId',accountId);const req=useData(`/privacy-requests?${query}`,version);return <><p className="admin-caption">L’approbation autorise le traitement ; elle ne déclenche pas la clôture. L’exécution est une étape distincte, contrôlée et journalisée.</p>{accountId&&<p className="admin-caption">Demandes du compte {accountId} · <Link to="/privacy-requests">Afficher tous les comptes</Link></p>}<DataState request={req}>{d=><><Table rows={(d.items||[]).map((r:Row)=>({...r,display_status:stateLabels[r.status]||r.status}))} cols={[['email','Compte'],['display_status','État'],['requested_at','Demande'],['approved_at','Approbation'],['completed_at','Fin'],['decision_reason','Motif']]} extra={r=><Link to={`/privacy-requests/${r.id}`} state={{from:location.pathname+location.search}}>Examiner la demande →</Link>}/><RequestPages total={d.total||0} count={d.items?.length||0}/></>}</DataState></>;}
export function PrivacyRequestDetail({id,user,action,version}:Props&{id:string}){const req=useData(`/privacy-requests/${encodeURIComponent(id)}`,version);const location=useLocation();const can=user.permissions.includes('privacy:write');return <><Link to={location.state?.from||'/privacy-requests'}>← Retour aux demandes</Link><DataState request={req}>{d=>{const r=d.request||{};return <section className="admin-panel"><h2>Clôture du compte {r.email||r.account_id}</h2><Badge value={stateLabels[r.status]||r.status}/><dl className="admin-facts"><div><dt>Demande reçue</dt><dd>{date(r.requested_at)}</dd></div><div><dt>Approbation</dt><dd>{date(r.approved_at)}</dd></div><div><dt>Fin du traitement</dt><dd>{date(r.completed_at)}</dd></div></dl>{r.decision_reason&&<p>Motif de décision : {r.decision_reason}</p>}{r.last_error&&<div className="admin-message" role="status">Traitement à vérifier : {r.last_error}. La clôture n’est pas annoncée comme terminée.</div>}<h3>Contrôles avant exécution</h3>{d.blockers?.length?<ul className="admin-reasons">{d.blockers.map((b:Row)=><li key={b.code}>{b.label}</li>)}</ul>:<p className="admin-caption">Aucun blocage signalé lors de cette consultation. Le serveur vérifie à nouveau les conditions à l’exécution.</p>}<p>La clôture retire l’accès au compte et anonymise le profil. L’historique métier nécessaire est conservé. Ce n’est pas une suppression instantanée de toutes les données.</p>{!can&&<p className="admin-caption">Votre rôle permet la consultation uniquement.</p>}<div className="admin-actions">{r.status==='REQUESTED'&&<Button disabled={!can} onClick={()=>action({title:'Approuver la demande de clôture',path:`/privacy-requests/${id}/approve`,consequence:'Cette approbation autorise une exécution ultérieure. Elle ne supprime ni accès ni données à cette étape.'})}>Approuver</Button>}{['REQUESTED','APPROVED'].includes(r.status)&&<Button variant="outline" disabled={!can} onClick={()=>action({title:'Refuser la demande de clôture',path:`/privacy-requests/${id}/reject`,consequence:'Le motif sera visible par le client. Le compte reste accessible selon son état actuel.'})}>Refuser</Button>}{['APPROVED','PROCESSING'].includes(r.status)&&<Button variant="danger" disabled={!can||!d.canExecute} onClick={()=>action({title:r.status==='PROCESSING'?'Reprendre la clôture':'Exécuter la clôture',path:`/privacy-requests/${id}/execute`,consequence:'Confirmez le retrait de l’accès au compte et l’anonymisation du profil. L’historique métier nécessaire est conservé. Les blocages sont vérifiés côté serveur ; un traitement incomplet peut nécessiter une reprise.'})}>{r.status==='PROCESSING'?'Reprendre le traitement':'Exécuter la clôture'}</Button>}</div>{['APPROVED','PROCESSING'].includes(r.status)&&!d.canExecute&&<p className="admin-caption">Exécution indisponible : consultez les blocages et l’état du traitement avant de réessayer.</p>}</section>;}}</DataState></>;}
