// Exhaustive local admin route/role smoke. API fixtures; never production mutations.
import {chromium} from 'playwright';import {createServer} from 'node:http';import {readFile,mkdir,writeFile} from 'node:fs/promises';import {resolve,extname} from 'node:path';import assert from 'node:assert/strict';import permissions from '../../../backend/.test-build/src/admin/permissions.js';
const root=resolve('dist-admin'),proof=resolve(process.env.ADMIN_AUDIT_DIR||'../annexe/proofs/admin-routes');await mkdir(proof,{recursive:true});
const server=createServer(async(req,res)=>{try{const path=resolve(root,'.'+(new URL(req.url,'http://localhost').pathname==='/'?'/index.html':new URL(req.url,'http://localhost').pathname));if(!path.startsWith(root+'/')&&!path.startsWith(root+'\\'))throw Error('outside');res.setHeader('Content-Type',({'.html':'text/html','.js':'application/javascript','.css':'text/css','.jpg':'image/jpeg','.webm':'video/webm','.vtt':'text/vtt','.ttf':'font/ttf'})[extname(path)]||'application/octet-stream');res.end(await readFile(path));}catch{res.writeHead(404);res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));
const origin=`http://127.0.0.1:${server.address().port}`,browser=await chromium.launch({headless:false,channel:'msedge'}),page=await browser.newPage(),errors=[],unexpected=[],results=[],failures=[];let role='OWNER',requests=[];
const aliases={'support-tickets':'accounts','personal-corrections':'accounts','privacy-requests':'accounts','recovery-requests':'accounts',executions:'jobs',operations:'sources',incidents:'infrastructure'};
const routes=['overview','support-tickets','accounts','accounts/fictional','personal-corrections','organizations','organizations/fictional','privacy-requests','privacy-requests/fictional','recovery-requests','missions','missions/fictional','missions/fictional/matching','jobs','sources','executions','operations','infrastructure','backups','audit','incidents','quality','access','does-not-exist'];
page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)failures.push({path:new URL(r.url()).pathname,status:r.status()});});
await page.route('**/api/**',async route=>{const request=route.request(),path=new URL(request.url()).pathname.replace('/api/v1/admin','');requests.push(path);if(request.method()!=='GET'){unexpected.push('Mutation '+path);return route.fulfill({status:405,json:{}});}let data;
if(path==='/me')data={id:'fixture-admin',email:'admin@example.invalid',role,permissions:permissions.ADMIN_PERMISSIONS[role],confirmedAt:new Date().toISOString()};
else if(path==='/overview')data={observedAt:new Date().toISOString(),counts:{accounts:1,organizations:1,missions:{OPEN:1}},alerts:[]};
else if(path==='/accounts/fictional')data={account:{id:'fictional',email:'client@example.invalid',family:'NURSE',active:true},profile:{qualifications:['IDE'],rpps_status:'NOT_CHECKED'},organizations:[],documents:[],audit:[]};
else if(path.endsWith('/email-deliveries'))data={items:[]};
else if(path.endsWith('/notifications'))data={connection:{state:'NOT_ASSOCIATED'},personal:{state:'NOT_ASSOCIATED'},internal:{total:0,unread:0},deliveries:{counts:{},recent:[]},organizations:[],catalog:{}};
else if(path.endsWith('/verification'))data={directory:{status:'NOT_CHECKED'},professionalIdentity:null,reviews:[]};
else if(path==='/organizations/fictional')data={organization:{id:'fictional',name:'Organisation fictive',kind:'ESTABLISHMENT',address:'Adresse fictive'},members:[],links:[]};
else if(path==='/missions/fictional')data={mission:{id:'fictional',title:'Mission fictive',status:'OPEN'},applications:[],assignments:[],events:[]};
else if(path==='/privacy-requests/fictional')data={request:{id:'fictional',status:'REQUESTED',email:'client@example.invalid'},blockers:[],canExecute:false};
else if(path==='/operations')data={observedAt:new Date().toISOString(),sources:[],incidents:[]};
else if(path==='/infrastructure')data={observedAt:new Date().toISOString(),services:[{name:'API fictive',state:'ready'}],version:'fixture'};
else if(path==='/backups')data={state:'unknown',message:'Preuve fictive indisponible',lastVerifiedAt:null};
else if(['/accounts','/organizations','/missions','/jobs','/sources','/executions','/audit','/incidents','/quality','/access','/support-tickets','/personal-corrections','/privacy-requests','/recovery-requests','/missions/fictional/matching'].includes(path))data={items:[],total:0,hasMore:false};
else{unexpected.push(path);return route.fulfill({status:501,json:{message:'Fixture manquante'}});}await route.fulfill({json:data});});
try{for(role of ['OWNER','SUPPORT','OPS','AUDITOR'])for(const path of routes){requests=[];await page.goto(origin+'/#/'+path);await page.reload();await page.locator('h1').waitFor();await page.waitForLoadState('networkidle');const permission=aliases[path.split('/')[0]]||path.split('/')[0],allowed=permissions.ADMIN_PERMISSIONS[role].includes(permission)&&(!path.endsWith('/matching')||permissions.ADMIN_PERMISSIONS[role].includes('matching'));const denied=await page.getByText(/Cette page n’existe pas ou votre rôle|Votre rôle ne permet pas la consultation du matching/).count();assert.equal(denied>0,!allowed,role+' '+path);if(!allowed)assert.deepEqual(requests.filter(x=>x!=='/me'),[],role+' requested forbidden resource '+path);for(const width of [320,768,1440]){await page.setViewportSize({width,height:900});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,role+' '+path+' overflow '+width);}results.push({role,route:'/#/'+path,allowed,denied:denied>0,widths:[320,768,1440]});}role='OWNER';await page.goto(origin+'/#/support-tickets');await page.reload();await page.getByText('Vidéo : trouver les guides de cet espace',{exact:true}).click();const media=await page.locator('video').evaluate(async v=>{v.muted=true;await v.play();await new Promise(r=>setTimeout(r,200));v.pause();return{duration:v.duration,error:v.error?.code??null};});assert.equal(media.error,null);assert.ok(media.duration>10);assert.deepEqual(errors,[]);assert.deepEqual(unexpected,[]);assert.deepEqual(failures,[]);await writeFile(resolve(proof,'admin-routes.json'),JSON.stringify({local:true,apiMocked:true,routes:results,jsErrors:errors,unexpectedRequests:unexpected,httpFailures:failures,adminHelpMedia:media},null,2));console.log('PASS '+results.length+' admin route/role checks x3 widths, forbidden resources not requested, guide media playable');}finally{await browser.close();await new Promise(r=>server.close(r));}
