// Isolated UI contract test. These fixtures never reach a production service.
import { chromium } from 'playwright';
import { createServer } from 'node:http';
import { readFile } from 'node:fs/promises';
import { resolve, extname } from 'node:path';
import assert from 'node:assert/strict';
const root = resolve('dist-admin');
const security=JSON.parse(await readFile(resolve(root,'vercel.json'),'utf8')).headers[0].headers;
const server = createServer(async (req, res) => {
  try {
    const path = resolve(root, '.' + (req.url === '/' ? '/index.html' : new URL(req.url, 'http://localhost').pathname));
    if (!path.startsWith(root + '/') && !path.startsWith(root + '\\')) throw Error('path');
    const data = await readFile(path); for(const h of security)res.setHeader(h.key,h.value); res.setHeader('Content-Type', ({ '.html': 'text/html', '.js': 'application/javascript', '.css': 'text/css' })[extname(path)] || 'application/octet-stream'); res.end(data);
  } catch { res.writeHead(404); res.end(); }
});
if (!process.env.BASE_URL) await new Promise(r => server.listen(0, '127.0.0.1', r));
const baseUrl=process.env.BASE_URL||`http://127.0.0.1:${server.address().port}/`;
const browser = await chromium.launch({ headless: true, channel: process.env.BROWSER_CHANNEL || (process.platform === 'win32' ? 'msedge' : undefined) });
try {
  const page = await browser.newPage(); const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  let invitationResponse='new'; let invitationChecks=0; let failPassword=false; let invitationLogins=0; let sessionExpiredEvents=0;
  const invitation='fixture-private-invitation-000000000000000000';
  let enrolling=false; let activations = 0; let authenticated = false; let fresh = false; let mutations = 0;
  const user = { id: 'fixture-admin', email: 'admin@example.invalid', role: 'SUPPORT', permissions: ['overview', 'accounts', 'accounts:write', 'organizations', 'missions', 'quality'], confirmedAt: new Date().toISOString() };
  await page.exposeFunction('recordSessionExpired',()=>sessionExpiredEvents++);
  await page.addInitScript(()=>window.addEventListener('admin-session-expired',()=>window.recordSessionExpired()));
  await page.route('**/api/v1/admin/**', async route => {
    const path = new URL(route.request().url()).pathname.replace('/api/v1/admin', ''); let status = 200; let body = {};
    if (path === '/me') { status = authenticated ? 200 : 401; body = authenticated ? user : {}; }
    else if (path === '/csrf') body = { csrfToken: 'isolated-fixture-csrf' };
    else if (path === '/invitation/check') { invitationChecks++; const payload=route.request().postDataJSON(); assert.equal(payload.email,user.email); assert.equal(payload.invitation,invitation); if(invitationResponse==='invalid') {status=401;} else body=invitationResponse==='malformed'?{passwordSetupRequired:'false'}:{passwordSetupRequired:invitationResponse==='new',csrfToken:'must-not-replace-csrf'}; }
    else if (path === '/activate') { activations++; const payload = route.request().postDataJSON(); assert.equal(payload.invitation, invitation); assert.equal(route.request().headers()['x-csrf-token'],'isolated-fixture-csrf'); assert.equal(payload.password, 'fixture-password-123'); assert.equal('passwordConfirmation' in payload, false); enrolling=true; body = {status:'MFA_ENROLLMENT_REQUIRED',secret:'JBSWY3DPEHPK3PXPJBSWY3DPEHPK3PXP',otpauthUri:'otpauth://totp/InfiMatch%20Admin%3Aadmin%40example.invalid?secret=JBSWY3DPEHPK3PXPJBSWY3DPEHPK3PXP&issuer=InfiMatch%20Admin&algorithm=SHA1&digits=6&period=30',csrfToken:'isolated-fixture-csrf'}; }
    else if (path === '/login') { const payload=route.request().postDataJSON(); if(payload.invitation){invitationLogins++;assert.equal(payload.invitation,invitation);} enrolling=false; if(failPassword){status=401;}else body = { status: 'MFA_REQUIRED', csrfToken: 'isolated-fixture-csrf' }; }
    else if(path==='/mfa/recover'){assert.deepEqual(route.request().postDataJSON(),{code:'a'.repeat(32)});enrolling=true;body={status:'MFA_ENROLLMENT_REQUIRED',secret:'JBSWY3DPEHPK3PXPJBSWY3DPEHPK3PXP',otpauthUri:'otpauth://totp/Fixture?secret=JBSWY3DPEHPK3PXPJBSWY3DPEHPK3PXP&issuer=Fixture'};}
    else if(path==='/mfa'){assert.deepEqual(route.request().postDataJSON(),{code:'123456'});authenticated=true;body={status:'AUTHENTICATED',csrfToken:'isolated-fixture-csrf',...(enrolling?{recoveryCodes:Array.from({length:8},(_,i)=>String(i).repeat(32))}:{})};}
    else if (path === '/overview') body = { observedAt: new Date().toISOString(), counts: { accounts: 1, organizations: 0, applications: 0, pendingEvents: 0, failedEvents: 0, documents: 0, missions: { OPEN: 0 } }, alerts: [{kind: 'backup', message: 'Fixture backup status', href: '/backups'}] };
    else if (path === '/executions') body = {items: [{id: 'fixture-run', state: 'completed', checked_at: '2026-09-17T10:00:00Z', execution_id: 'fixture-execution', workflow_id: 'fixture/unsafe?fragment', action: 'confirmation', duration_ms: 125}], total: 1, limit: 20, offset: 0};
    else if(path.endsWith('/email-deliveries'))body={items:[]};
    else if(path.endsWith('/notifications'))body={connection:{state:'NOT_ASSOCIATED'},personal:{state:'NOT_ASSOCIATED'},internal:{total:0,unread:0},deliveries:{counts:{},recent:[]},organizations:[],catalog:{}};
    else if (path === '/accounts') body = { items: [{ id: 'fixture-account', email: 'client@example.invalid', family: 'NURSE', active: true }], total: 1, limit: 20, offset: 0 };
    else if (path === '/accounts/fixture-account/verification') body = {directory: {status:'FOUND'}, professionalIdentity:null, reviews:[]};
    else if (path === '/accounts/fixture-account') body = { account: { id: 'fixture-account', email: 'client@example.invalid', active: true, family:'NURSE' }, organizations: [{name: 'Organisation fictive', kind: 'ESTABLISHMENT', active: true}], profile: {display_name: 'Profil fictif', qualifications: ['IDE', 'IADE'], rpps_status: 'FOUND', rpps_checked_at: '2026-09-17T10:00:00Z'}, documents: [], audit: [{event: 'FIXTURE_AUDIT', created_at: '2026-09-17T10:00:00Z'}] };
    else if (path === '/accounts/fixture-account/state') { assert.equal(route.request().headers()['x-csrf-token'], 'isolated-fixture-csrf'); if (!fresh) { status = 403; body = { code: 'ADMIN_REAUTH_REQUIRED' }; } else { mutations++; body = { ok: true }; } }
    else if (path === '/reauth') {assert.deepEqual(route.request().postDataJSON(), {password:'test-only-password',code:'654321'});fresh = true;}
    else if (path === '/logout') authenticated = false;
    else throw new Error(`Unexpected fixture endpoint: ${path}`);
    await route.fulfill({ status, json: body });
  });
  await page.goto(baseUrl);
  await page.getByRole('heading',{name:'Connexion sécurisée',exact:true}).waitFor();
  await page.setViewportSize({width:375,height:812});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'No overflow on the mobile connection form');
  await page.getByLabel('Adresse e-mail',{exact:true}).fill(user.email);
  await page.getByRole('button', {name:'J’ai reçu une invitation',exact:true}).focus();
  await page.keyboard.press('Enter');
  assert.equal(await page.getByRole('heading',{name:'Vérifier votre invitation',exact:true}).evaluate(el=>el===document.activeElement),true,'The invitation heading receives focus after keyboard navigation');
  assert.equal(await page.getByRole('button',{name:'J’ai reçu une invitation',exact:true}).getAttribute('aria-pressed'),'true');
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'No overflow on the mobile invitation form');
  assert.equal(await page.getByLabel('Adresse e-mail',{exact:true}).inputValue(),user.email,'Switching paths retains email');
  assert.equal(await page.getByLabel('Mot de passe',{exact:true}).count(),0,'No password before invitation check');
  await page.getByLabel('Code d’invitation administrateur',{exact:true}).fill(invitation);
  invitationResponse='invalid';
  const expiredBefore=sessionExpiredEvents;
  await page.getByRole('button',{name:'Vérifier mon invitation',exact:true}).click();
  await page.getByRole('alert').filter({hasText:'Invitation invalide, expirée ou déjà utilisée.'}).waitFor();
  assert.equal(sessionExpiredEvents,expiredBefore,'Invalid invitation never expires an existing admin session');
  invitationResponse='malformed';
  await page.getByRole('button',{name:'Vérifier mon invitation',exact:true}).click();
  await page.getByRole('alert').filter({hasText:'La réponse du service est inattendue.'}).waitFor();
  assert.equal(await page.getByLabel('Mot de passe',{exact:true}).count(),0,'Malformed response cannot choose a password path');
  invitationResponse='existing';
  await page.getByRole('button',{name:'Vérifier mon invitation',exact:true}).click();
  await page.getByRole('heading',{name:'Utiliser votre mot de passe',exact:true}).waitFor();
  assert.equal(await page.getByLabel('Adresse e-mail',{exact:true}).count(),0,'Verified email is no longer editable');
  assert.equal(await page.getByLabel('Confirmer le nouveau mot de passe',{exact:true}).count(),0);
  await page.getByLabel('Mot de passe',{exact:true}).fill('wrong-fixture-password');
  failPassword=true;
  await page.getByRole('button',{name:'Continuer',exact:true}).click();
  await page.getByRole('alert').filter({hasText:'Connexion impossible.'}).waitFor();
  assert.equal(invitationChecks,3,'Wrong password does not recheck or reactivate the account');
  assert.equal(invitationLogins,1);assert.equal(activations,0);
  failPassword=false;
  await page.getByRole('button',{name:'Corriger l’invitation',exact:true}).click();
  assert.equal(await page.getByLabel('Mot de passe',{exact:true}).count(),0);
  invitationResponse='new';
  await page.getByRole('button',{name:'Vérifier mon invitation',exact:true}).click();
  await page.getByRole('heading',{name:'Créer votre mot de passe',exact:true}).waitFor();
  assert.equal(await page.getByRole('heading',{name:'Créer votre mot de passe',exact:true}).evaluate(el=>el===document.activeElement),true,'The password step announces its heading');
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'No overflow on the mobile password form');
  assert.equal(await page.getByLabel('Nouveau mot de passe (12 caractères minimum)',{exact:true}).inputValue(),'','Correcting invitation clears old passwords');
  await page.getByLabel('Nouveau mot de passe (12 caractères minimum)',{exact:true}).fill('fixture-password-123');
  await page.getByLabel('Confirmer le nouveau mot de passe',{exact:true}).fill('fixture-mismatch-123');
  await page.getByRole('button',{name:'Continuer',exact:true}).click();
  await page.getByText('Les deux mots de passe doivent être identiques.').waitFor();
  assert.equal(activations,0,'Mismatched confirmation never calls activation');
  await page.getByLabel('Confirmer le nouveau mot de passe',{exact:true}).fill('fixture-password-123');
  await page.getByRole('button',{name:'Continuer',exact:true}).click();
  await page.getByRole('heading',{name:'Configurer la double authentification',exact:true}).waitFor();
  assert.equal(await page.getByRole('heading',{name:'Vue d’ensemble',exact:true}).count(),0);
  const qr=page.getByRole('img',{name:'QR code à scanner dans votre application d’authentification'});await qr.waitFor();
  assert.ok(await qr.locator('path').count()>0);
  assert.equal(await page.getByLabel('Clé de configuration confidentielle').isVisible(),false);
  await page.getByText('Je ne peux pas scanner le QR code',{exact:true}).click();
  assert.equal(await page.getByLabel('Clé de configuration confidentielle').inputValue(),'JBSWY3DPEHPK3PXPJBSWY3DPEHPK3PXP');
  await page.setViewportSize({width:375,height:812});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  await page.screenshot({path:'artifacts/admin-mfa-qr-fixture.png',fullPage:true});
  await page.setViewportSize({width:1280,height:900});
  await page.getByLabel('Code de sécurité',{exact:true}).fill('123456');await page.getByRole('button',{name:'Vérifier',exact:true}).click();
  await page.getByRole('heading',{name:'Conserver vos codes de secours'}).waitFor();await page.getByLabel('J’ai conservé mes codes dans un endroit sûr.').check();
  await page.getByRole('button',{name:'Accéder à l’administration'}).click();
  await page.getByRole('heading',{name:'Vue d’ensemble',exact:true}).waitFor();
  assert.equal(activations,1);
  assert.equal(page.url().includes('fixture-private-invitation'),false);
  assert.equal(page.url().includes('fixture-password'),false);
  await page.getByRole('heading',{name:'Vue d’ensemble',exact:true}).waitFor();
  assert.equal(await page.getByLabel('Lien de configuration',{exact:true}).count(),0);
  await page.getByRole('button',{name:'Se déconnecter'}).click();
  await page.getByRole('button',{name:'J’ai reçu une invitation',exact:true}).click();
  await page.getByLabel('Adresse e-mail',{exact:true}).fill(user.email);
  await page.getByLabel('Code d’invitation administrateur',{exact:true}).fill(invitation);
  invitationResponse='existing';
  await page.getByRole('button',{name:'Vérifier mon invitation',exact:true}).click();
  await page.getByLabel('Mot de passe',{exact:true}).fill('fixture-password-123');
  await page.getByRole('button',{name:'Continuer',exact:true}).click();
  await page.getByRole('heading',{name:'Vérifier votre identité',exact:true}).waitFor();
  assert.equal(activations,1,'An existing account never calls activation');
  assert.equal(invitationLogins,2);
  await page.getByRole('button',{name:'Utiliser un code de secours',exact:true}).click();
  await page.getByLabel('Code de secours',{exact:true}).fill('a'.repeat(32));
  await page.getByRole('button',{name:'Vérifier',exact:true}).click();
  await page.getByRole('heading',{name:'Configurer la double authentification',exact:true}).waitFor();
  assert.equal(await page.getByRole('heading',{name:'Vue d’ensemble',exact:true}).count(),0,'Recovery does not bypass reenrollment');
  await page.getByRole('button',{name:'Revenir à la connexion',exact:true}).click();
  await page.getByRole('heading',{name:'Connexion sécurisée',exact:true}).waitFor();
  await page.getByLabel('Adresse e-mail', { exact: true }).fill('admin@example.invalid');
  await page.getByLabel('Mot de passe', { exact: true }).fill('test-only-password');
  await page.getByRole('button', { name: 'Se connecter', exact: true }).click();
  await page.getByLabel('Code de sécurité',{exact:true}).fill('123456');await page.getByRole('button',{name:'Vérifier',exact:true}).click();
  await page.getByRole('heading', { name: 'Vue d’ensemble', exact: true }).waitFor();
  assert.equal(await page.getByRole('link', { name: 'Accès administrateurs' }).count(), 0);
  assert.equal(await page.locator('a[href*="jobs"],a[href*="backups"]').count(), 0, 'Overview destinations obey SUPPORT permissions');
  await page.getByRole('link', { name: 'Comptes et dossiers', exact: true }).click();
  await page.getByRole('link', { name: 'Consulter →', exact: true }).click();
  await page.getByText('IDE, IADE', { exact: true }).waitFor();
  await page.getByRole('columnheader', { name: 'Rattachement actif' }).waitFor();
  assert.equal(await page.getByText('?v?nement', { exact: true }).count(), 0);
  await page.getByRole('button', { name: 'Suspendre', exact: true }).click();
  assert.equal(await page.getByLabel('Justification (journalisée)').getAttribute('maxlength'), '500');
  await page.getByLabel('Justification (journalisée)').fill('Test isolé de confirmation motivée');
  await page.getByRole('button', { name: 'Confirmer l’opération' }).click();
  await page.getByLabel('Confirmer votre mot de passe').fill('test-only-password');
  await page.getByLabel('Code de sécurité',{exact:true}).fill('654321');
  await page.getByRole('button', { name: 'Confirmer mon identité' }).click();
  assert.equal(mutations, 0, 'No automatic mutation after reauthentication');
  await page.getByRole('button', { name: 'Confirmer l’opération' }).click();
  await page.getByText('Opération enregistrée. Les données ont été actualisées.').waitFor();
  assert.equal(mutations, 1);
  await page.setViewportSize({ width: 390, height: 844 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, 'No mobile page overflow');
  await page.getByRole('button', { name: 'Se déconnecter' }).click();
  await page.getByRole('heading', { name: 'Connexion sécurisée' }).waitFor();
  authenticated = true; user.role = 'OPS'; user.permissions = ['overview', 'jobs'];
  await page.reload();
  await page.getByRole('link', { name: 'Exécutions', exact: true }).click();
  await page.getByText('fixture-execution', {exact: true}).waitFor();
  assert.equal(await page.getByRole('link', {name: 'Voir le workflow n8n (nouvel onglet)'}).getAttribute('href'), 'https://infimatch.app.n8n.cloud/workflow/fixture%2Funsafe%3Ffragment');
  assert.deepEqual(errors, []);
  let broken = true;
  await page.route('**/api/v1/admin/overview',route=>route.fulfill({json:broken?{counts:{accounts:{unexpected:true}}}:{counts:{accounts:0,organizations:0,missions:{}},alerts:[]}}));
  await page.getByRole('link',{name:'Vue d’ensemble',exact:true}).click();
  await page.getByRole('heading',{name:'L’administration ne peut pas afficher cette page',exact:true}).waitFor();
  assert.ok(!(await page.locator('body').innerText()).includes('Objects are not valid'));
  broken = false;
  await page.getByRole('button',{name:'Réessayer',exact:true}).click();
  await page.getByRole('heading',{name:'Vue d’ensemble',exact:true}).waitFor();
  console.log('PASS admin malformed response: accessible fallback and recovery without mutation replay');
  console.log('PASS invitation: new/existing accounts, invalid and malformed responses, password retry, recovery reenrollment, no CSRF replacement or activation replay.');
  console.log('PASS isolated admin UI: MFA enrollment/login, recovery-code acknowledgement, role navigation, reason, CSRF, explicit reauth retry, mobile, logout. Backend authentication not tested by this fixture.');
} finally { await browser.close(); if(server.listening) await new Promise(r => server.close(r)); }
