import { MATCH_RULES } from "../domain/rules";
import { Controller, Get, Module } from "@nestjs/common";
export const ideServices = [
  "CARDIOLOGIE",
  "PNEUMOLOGIE",
  "NEUROLOGIE",
  "GASTRO_ENTEROLOGIE",
  "NEPHROLOGIE",
  "ENDOCRINOLOGIE",
  "INFECTIOLOGIE",
  "DERMATOLOGIE",
  "RHUMATOLOGIE",
  "CHIRURGIE",
  "URGENCES",
  "REANIMATION",
  "SOINS_INTENSIFS",
  "SSPI",
  "PEDIATRIE",
  "NEONATOLOGIE",
  "GYNECOLOGIE",
  "MATERNITE",
  "ONCOLOGIE",
  "HEMATOLOGIE",
  "DIALYSE",
  "PSYCHIATRIE",
  "PEDOPSYCHIATRIE",
  "ADDICTOLOGIE",
  "GERIATRIE",
  "SOINS_LONGUE_DUREE",
  "EHPAD",
  "SMR",
  "SOINS_PALLIATIFS",
  "DOULEUR",
  "CONSULTATIONS",
  "HOPITAL_JOUR",
  "CHIRURGIE_AMBULATOIRE",
  "ENDOSCOPIE",
  "EXPLORATIONS",
  "INTERVENTIONNEL",
  "MAS",
  "FAM",
  "HAD",
  "DOMICILE_SALARIE",
  "SANTE_TRAVAIL",
  "PREVENTION",
  "CENTRE_SANTE",
  "SUPPLEANCE",
  "AUTRE",
];
export const blockSpecialties = [
  "ORTHOPEDIE_TRAUMATOLOGIE",
  "DIGESTIF",
  "UROLOGIE",
  "GYNECOLOGIE_OBSTETRIQUE",
  "ORL",
  "OPHTALMOLOGIE",
  "NEUROCHIRURGIE",
  "CARDIAQUE",
  "THORACIQUE",
  "VASCULAIRE",
  "PLASTIQUE",
  "MAXILLO_FACIALE",
];
@Controller("reference-data")
class ReferenceController {
  @Get() get() {
    return {
      qualifications: ["IDE", "IADE", "IBODE"],
      ideServices,
      blockSpecialties,
      populations: ["ADULT", "PEDIATRIC", "MIXED"],
      blocks: ["NONE", "GENERAL", "SPECIALIZED"],
      shifts: ["DAY", "NIGHT", "MIXED"],
      salary: { currency: "EUR", unit: "HOUR", gross: true },
      timezone: "Europe/Paris",
      intervalConvention: "[start,end)",
      search: {
        sameDimension: "OR",
        withinBranch: "AND",
        branches: "OR",
        dateWindow: "OVERLAP",
      },
      matching: MATCH_RULES,
      limits: {
        pageSize: 20,
        maxPageSize: 50,
        maxRadiusKm: 1000,
        documentMiB: 5,
      },
      termsVersion: "2026-09-14",
    };
  }
}
@Module({ controllers: [ReferenceController] })
export class ReferenceDataModule {}
