import {Injectable,ServiceUnavailableException,UnauthorizedException} from '@nestjs/common';
import * as oidc from 'openid-client';
const environments={sandbox:{issuer:'https://auth.bas.psc.esante.gouv.fr/auth/realms/esante-wallet',wallet:'https://wallet.bas.psc.esante.gouv.fr'},production:{issuer:'https://auth.esw.esante.gouv.fr/auth/realms/esante-wallet',wallet:'https://wallet.esw.esante.gouv.fr'}};
export function pscConfiguration(){if(process.env.PSC_ENABLED!=='true'||!process.env.PSC_CLIENT_ID||!process.env.PSC_CLIENT_SECRET)return null;const environment=process.env.PSC_ENVIRONMENT;if(environment!=='sandbox'&&environment!=='production')return null;return {...environments[environment],clientId:process.env.PSC_CLIENT_ID,secret:process.env.PSC_CLIENT_SECRET,callback:process.env.APP_ORIGIN+'/api/v1/auth/psc/callback'};}
export function pscIdentity(info:Record<string,unknown>){if(typeof info.sub!=='string'||!info.sub||typeof info.SubjectNameID!=='string'||!info.SubjectNameID.trim()||info.SubjectNameID.length>200)throw new UnauthorizedException('PSC_IDENTITY_INCOMPLETE');return {subject:info.sub,subjectNameId:info.SubjectNameID};}
@Injectable()
export class PscProvider {
 private cache?:{expires:number;client:oidc.Configuration};
 async client(){const conf=pscConfiguration();if(!conf)throw new ServiceUnavailableException('PSC_DISABLED');if(this.cache&&this.cache.expires>Date.now())return this.cache.client;
 const response=await fetch(conf.issuer+'/.well-known/wallet-openid-configuration',{signal:AbortSignal.timeout(8000),redirect:'error'});if(!response.ok)throw new ServiceUnavailableException('PSC_UNAVAILABLE');const metadata=await response.json() as oidc.ServerMetadata;
 if(metadata.issuer!==conf.issuer)throw new UnauthorizedException('PSC_ISSUER_MISMATCH');
 for(const field of ['authorization_endpoint','token_endpoint','userinfo_endpoint','jwks_uri'] as const){const raw=metadata[field];if(typeof raw!=='string')throw new UnauthorizedException('PSC_INVALID_METADATA');const url=new URL(raw);if(url.protocol!=='https:'||url.username||url.password||![new URL(conf.issuer).origin,conf.wallet].includes(url.origin))throw new UnauthorizedException('PSC_INVALID_METADATA');}
 const client=new oidc.Configuration(metadata,conf.clientId,{token_endpoint_auth_method:'client_secret_post',id_token_signed_response_alg:'RS256'},oidc.ClientSecretPost(conf.secret));client.timeout=8;oidc.enableNonRepudiationChecks(client);this.cache={client,expires:Date.now()+3600000};return client;}
 async begin(){const conf=pscConfiguration();if(!conf)throw new ServiceUnavailableException('PSC_DISABLED');const client=await this.client(),state=oidc.randomState(),nonce=oidc.randomNonce(),verifier=oidc.randomPKCECodeVerifier();const pkce=client.serverMetadata().code_challenge_methods_supported?.includes('S256');const url=oidc.buildAuthorizationUrl(client,{redirect_uri:conf.callback,scope:'openid scope_all',state,nonce,...(pkce?{code_challenge:await oidc.calculatePKCECodeChallenge(verifier),code_challenge_method:'S256'}:{})});return {url:url.href,state,nonce,verifier:pkce?verifier:''};}
 async complete(url:URL,expected:{state:string;nonce:string;verifier:string}){const client=await this.client();const tokens=await oidc.authorizationCodeGrant(client,url,{expectedState:expected.state,expectedNonce:expected.nonce,idTokenExpected:true,...(expected.verifier?{pkceCodeVerifier:expected.verifier}:{})});const claims=tokens.claims();if(!claims?.sub)throw new UnauthorizedException('PSC_INVALID_TOKEN');const info=await oidc.fetchUserInfo(client,tokens.access_token,claims.sub);return pscIdentity(info);}
}
